export const cars = [
    {
      id: "1",
      make: "Toyota",
      model: "Corolla",
      year: 2022,
      price: 1500000,
      fuel: "Petrol",
      mileage: "18 km/l",
      image: "https://via.placeholder.com/300x200.png?text=Toyota+Corolla",
    },
    {
      id: "2",
      make: "Honda",
      model: "Civic",
      year: 2023,
      price: 1800000,
      fuel: "Diesel",
      mileage: "20 km/l",
      image: "https://via.placeholder.com/300x200.png?text=Honda+Civic",
    },
    {
        id: "3",
        make: "Toyota",
        model: "Corolla",
        year: 2022,
        price: 1500000,
        fuel: "Petrol",
        mileage: "18 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Toyota+Corolla",
      },
      {
        id: "4",
        make: "Honda",
        model: "Civic",
        year: 2023,
        price: 1800000,
        fuel: "Diesel",
        mileage: "20 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Honda+Civic",
      },
      {
        id: "5",
        make: "Toyota",
        model: "Corolla",
        year: 2022,
        price: 1500000,
        fuel: "Petrol",
        mileage: "18 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Toyota+Corolla",
      },
      {
        id: "6",
        make: "Honda",
        model: "Civic",
        year: 2023,
        price: 1800000,
        fuel: "Diesel",
        mileage: "20 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Honda+Civic",
      },
      {
        id: "7",
        make: "Toyota",
        model: "Corolla",
        year: 2022,
        price: 1500000,
        fuel: "Petrol",
        mileage: "18 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Toyota+Corolla",
      },
      {
        id: "8",
        make: "Honda",
        model: "Civic",
        year: 2023,
        price: 1800000,
        fuel: "Diesel",
        mileage: "20 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Honda+Civic",
      },
      {
        id: "9",
        make: "Toyota",
        model: "Corolla",
        year: 2022,
        price: 1500000,
        fuel: "Petrol",
        mileage: "18 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Toyota+Corolla",
      },
      {
        id: "10",
        make: "Honda",
        model: "Civic",
        year: 2023,
        price: 1800000,
        fuel: "Diesel",
        mileage: "20 km/l",
        image: "https://via.placeholder.com/300x200.png?text=Honda+Civic",
      },
  ];
  