export const cars = [
  {
    "id": "1",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2013,
    "price": 729410,
    "originalPrice": 867407,
    "fuel": "Diesel",
    "mileage": "14.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "AC",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "2",
    "make": "Kia",
    "model": "Malibu",
    "year": 2016,
    "price": 571929,
    "originalPrice": 753179,
    "fuel": "Petrol",
    "mileage": "12.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "AC",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "3",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2012,
    "price": 675454,
    "originalPrice": 870700,
    "fuel": "Petrol",
    "mileage": "22.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "ABS",
      "Navigation",
      "AC"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "4",
    "make": "Honda",
    "model": "Sportage",
    "year": 2016,
    "price": 1420842,
    "originalPrice": 1483724,
    "fuel": "Hybrid",
    "mileage": "17.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "5",
    "make": "BMW",
    "model": "Corolla",
    "year": 2012,
    "price": 1019305,
    "originalPrice": 1111822,
    "fuel": "Hybrid",
    "mileage": "11.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "ABS",
      "Bluetooth",
      "Navigation",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "6",
    "make": "Mercedes",
    "model": "Civic",
    "year": 2022,
    "price": 1295638,
    "originalPrice": 1481567,
    "fuel": "Diesel",
    "mileage": "16.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "7",
    "make": "Tesla",
    "model": "C-Class",
    "year": 2020,
    "price": 539657,
    "originalPrice": 559092,
    "fuel": "Petrol",
    "mileage": "12.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "AC",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "8",
    "make": "BMW",
    "model": "Elantra",
    "year": 2018,
    "price": 1476229,
    "originalPrice": 1592938,
    "fuel": "Electric",
    "mileage": "23.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "AC",
      "Power Steering",
      "ABS",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "9",
    "make": "Ford",
    "model": "Q7",
    "year": 2011,
    "price": 562368,
    "originalPrice": 732645,
    "fuel": "Hybrid",
    "mileage": "19.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Navigation",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "10",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2013,
    "price": 1290986,
    "originalPrice": 1327319,
    "fuel": "Petrol",
    "mileage": "18.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Power Steering",
      "Bluetooth",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "11",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2019,
    "price": 930162,
    "originalPrice": 1011572,
    "fuel": "Hybrid",
    "mileage": "21.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Airbags",
      "Navigation",
      "Bluetooth",
      "Leather Seats",
      "AC",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "12",
    "make": "Kia",
    "model": "X5",
    "year": 2023,
    "price": 1067553,
    "originalPrice": 1163638,
    "fuel": "Petrol",
    "mileage": "19.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Leather Seats",
      "AC",
      "ABS",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "13",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2017,
    "price": 1016091,
    "originalPrice": 1172086,
    "fuel": "Diesel",
    "mileage": "16.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Leather Seats",
      "ABS",
      "Power Steering",
      "AC"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "14",
    "make": "Ford",
    "model": "Corolla",
    "year": 2022,
    "price": 1444948,
    "originalPrice": 1534810,
    "fuel": "Diesel",
    "mileage": "18.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Power Steering",
      "AC"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "15",
    "make": "Toyota",
    "model": "Q7",
    "year": 2013,
    "price": 1293604,
    "originalPrice": 1404310,
    "fuel": "Hybrid",
    "mileage": "18.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Sunroof",
      "Power Steering",
      "AC",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "16",
    "make": "Chevrolet",
    "model": "X5",
    "year": 2016,
    "price": 637599,
    "originalPrice": 652707,
    "fuel": "Diesel",
    "mileage": "16.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Navigation",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "17",
    "make": "BMW",
    "model": "Model 3",
    "year": 2018,
    "price": 547984,
    "originalPrice": 663832,
    "fuel": "Electric",
    "mileage": "20.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "Navigation",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "18",
    "make": "Ford",
    "model": "C-Class",
    "year": 2020,
    "price": 741740,
    "originalPrice": 885690,
    "fuel": "Hybrid",
    "mileage": "15.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Power Steering",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "19",
    "make": "Audi",
    "model": "C-Class",
    "year": 2024,
    "price": 1312191,
    "originalPrice": 1389711,
    "fuel": "Diesel",
    "mileage": "21.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Navigation",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "20",
    "make": "Hyundai",
    "model": "Civic",
    "year": 2019,
    "price": 926468,
    "originalPrice": 1028357,
    "fuel": "Electric",
    "mileage": "17.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Airbags",
      "Navigation",
      "AC"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "21",
    "make": "Honda",
    "model": "Q7",
    "year": 2017,
    "price": 586267,
    "originalPrice": 633769,
    "fuel": "Petrol",
    "mileage": "16.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "AC",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "22",
    "make": "Hyundai",
    "model": "X5",
    "year": 2023,
    "price": 561259,
    "originalPrice": 722688,
    "fuel": "Petrol",
    "mileage": "22.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "23",
    "make": "Kia",
    "model": "Civic",
    "year": 2022,
    "price": 824533,
    "originalPrice": 847782,
    "fuel": "Petrol",
    "mileage": "13.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Navigation",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "24",
    "make": "Mercedes",
    "model": "Q7",
    "year": 2015,
    "price": 782633,
    "originalPrice": 844417,
    "fuel": "Petrol",
    "mileage": "18.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "ABS",
      "Power Steering",
      "AC",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "25",
    "make": "Kia",
    "model": "X5",
    "year": 2013,
    "price": 806087,
    "originalPrice": 1000331,
    "fuel": "Diesel",
    "mileage": "19.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "ABS",
      "Airbags",
      "Bluetooth",
      "Leather Seats",
      "Sunroof",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "26",
    "make": "Ford",
    "model": "Corolla",
    "year": 2016,
    "price": 728362,
    "originalPrice": 917076,
    "fuel": "Hybrid",
    "mileage": "22.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Leather Seats",
      "Airbags",
      "Bluetooth",
      "AC",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "27",
    "make": "Tesla",
    "model": "X5",
    "year": 2011,
    "price": 1118275,
    "originalPrice": 1315908,
    "fuel": "Diesel",
    "mileage": "10.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Power Steering",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "28",
    "make": "Audi",
    "model": "X5",
    "year": 2010,
    "price": 508543,
    "originalPrice": 519294,
    "fuel": "Diesel",
    "mileage": "24.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Airbags",
      "Sunroof",
      "AC"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "29",
    "make": "Audi",
    "model": "Malibu",
    "year": 2024,
    "price": 1133104,
    "originalPrice": 1311497,
    "fuel": "Diesel",
    "mileage": "24.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Sunroof",
      "Leather Seats",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "30",
    "make": "Kia",
    "model": "Model 3",
    "year": 2011,
    "price": 1276737,
    "originalPrice": 1364532,
    "fuel": "Diesel",
    "mileage": "15.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Navigation",
      "Power Steering",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "31",
    "make": "Audi",
    "model": "Malibu",
    "year": 2018,
    "price": 643848,
    "originalPrice": 701680,
    "fuel": "Petrol",
    "mileage": "21.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "AC",
      "Leather Seats",
      "ABS",
      "Sunroof",
      "Power Steering",
      "Navigation"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "32",
    "make": "Tesla",
    "model": "Model 3",
    "year": 2024,
    "price": 906990,
    "originalPrice": 1035521,
    "fuel": "Petrol",
    "mileage": "22.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Airbags",
      "Leather Seats",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "33",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2017,
    "price": 593143,
    "originalPrice": 648334,
    "fuel": "Hybrid",
    "mileage": "20.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "AC",
      "Navigation",
      "Bluetooth",
      "Airbags",
      "ABS",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "34",
    "make": "Toyota",
    "model": "Civic",
    "year": 2017,
    "price": 1262483,
    "originalPrice": 1317795,
    "fuel": "Electric",
    "mileage": "16.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "35",
    "make": "BMW",
    "model": "C-Class",
    "year": 2021,
    "price": 1153155,
    "originalPrice": 1286721,
    "fuel": "Hybrid",
    "mileage": "15.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Navigation",
      "Sunroof",
      "Airbags",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "36",
    "make": "Kia",
    "model": "Sportage",
    "year": 2012,
    "price": 1202626,
    "originalPrice": 1334320,
    "fuel": "Electric",
    "mileage": "22.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "37",
    "make": "Ford",
    "model": "Sportage",
    "year": 2021,
    "price": 534845,
    "originalPrice": 650873,
    "fuel": "Electric",
    "mileage": "13.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "Power Steering",
      "Airbags",
      "Bluetooth",
      "AC",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "38",
    "make": "Ford",
    "model": "X5",
    "year": 2017,
    "price": 573336,
    "originalPrice": 753597,
    "fuel": "Petrol",
    "mileage": "23.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "39",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2010,
    "price": 623584,
    "originalPrice": 796907,
    "fuel": "Petrol",
    "mileage": "22.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "Sunroof",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "40",
    "make": "Kia",
    "model": "Elantra",
    "year": 2015,
    "price": 1422627,
    "originalPrice": 1545985,
    "fuel": "Hybrid",
    "mileage": "24.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Airbags",
      "ABS",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "41",
    "make": "Kia",
    "model": "Sportage",
    "year": 2010,
    "price": 1221474,
    "originalPrice": 1339802,
    "fuel": "Hybrid",
    "mileage": "15.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Power Steering",
      "Leather Seats",
      "Bluetooth",
      "Navigation",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "42",
    "make": "BMW",
    "model": "Malibu",
    "year": 2015,
    "price": 832870,
    "originalPrice": 969476,
    "fuel": "Hybrid",
    "mileage": "21.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "43",
    "make": "Audi",
    "model": "Corolla",
    "year": 2023,
    "price": 619770,
    "originalPrice": 756955,
    "fuel": "Electric",
    "mileage": "19.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "Power Steering",
      "Sunroof",
      "ABS",
      "AC"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "44",
    "make": "Kia",
    "model": "Sportage",
    "year": 2010,
    "price": 1416779,
    "originalPrice": 1441616,
    "fuel": "Electric",
    "mileage": "17.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Power Steering",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "45",
    "make": "Mercedes",
    "model": "Corolla",
    "year": 2016,
    "price": 1035041,
    "originalPrice": 1162752,
    "fuel": "Hybrid",
    "mileage": "18.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "AC",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "46",
    "make": "BMW",
    "model": "Q7",
    "year": 2016,
    "price": 1261513,
    "originalPrice": 1269712,
    "fuel": "Hybrid",
    "mileage": "21.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "Airbags",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "47",
    "make": "Mercedes",
    "model": "Model 3",
    "year": 2011,
    "price": 842166,
    "originalPrice": 846637,
    "fuel": "Electric",
    "mileage": "11.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Navigation",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "48",
    "make": "Hyundai",
    "model": "Sportage",
    "year": 2015,
    "price": 814133,
    "originalPrice": 896328,
    "fuel": "Electric",
    "mileage": "21.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "49",
    "make": "Tesla",
    "model": "C-Class",
    "year": 2020,
    "price": 693129,
    "originalPrice": 890503,
    "fuel": "Petrol",
    "mileage": "16.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "AC",
      "Sunroof",
      "ABS",
      "Power Steering",
      "Navigation",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "50",
    "make": "Audi",
    "model": "Mustang",
    "year": 2020,
    "price": 966136,
    "originalPrice": 980164,
    "fuel": "Electric",
    "mileage": "17.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Navigation",
      "ABS",
      "Sunroof",
      "Airbags",
      "AC"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "51",
    "make": "Honda",
    "model": "Model 3",
    "year": 2017,
    "price": 626562,
    "originalPrice": 737816,
    "fuel": "Hybrid",
    "mileage": "19.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Airbags",
      "AC",
      "Navigation",
      "Leather Seats",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "52",
    "make": "Kia",
    "model": "Civic",
    "year": 2012,
    "price": 636798,
    "originalPrice": 835442,
    "fuel": "Diesel",
    "mileage": "13.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "53",
    "make": "Ford",
    "model": "C-Class",
    "year": 2019,
    "price": 1436737,
    "originalPrice": 1530193,
    "fuel": "Diesel",
    "mileage": "19.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "54",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2022,
    "price": 992067,
    "originalPrice": 1181899,
    "fuel": "Electric",
    "mileage": "12.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "Bluetooth",
      "Power Steering",
      "ABS",
      "Airbags",
      "AC"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "55",
    "make": "Toyota",
    "model": "Model 3",
    "year": 2017,
    "price": 1267783,
    "originalPrice": 1458039,
    "fuel": "Electric",
    "mileage": "14.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Sunroof",
      "Navigation",
      "Leather Seats",
      "AC"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "56",
    "make": "Tesla",
    "model": "Model 3",
    "year": 2016,
    "price": 1394727,
    "originalPrice": 1497063,
    "fuel": "Petrol",
    "mileage": "15.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Power Steering",
      "AC",
      "Leather Seats",
      "Navigation",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "57",
    "make": "Kia",
    "model": "Q7",
    "year": 2021,
    "price": 1492294,
    "originalPrice": 1561227,
    "fuel": "Hybrid",
    "mileage": "21.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Airbags",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "58",
    "make": "Kia",
    "model": "Elantra",
    "year": 2014,
    "price": 1307069,
    "originalPrice": 1480143,
    "fuel": "Petrol",
    "mileage": "15.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Airbags",
      "Power Steering",
      "Navigation",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "59",
    "make": "BMW",
    "model": "C-Class",
    "year": 2011,
    "price": 718040,
    "originalPrice": 779628,
    "fuel": "Hybrid",
    "mileage": "23.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Power Steering",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "60",
    "make": "Honda",
    "model": "Mustang",
    "year": 2013,
    "price": 1127294,
    "originalPrice": 1259669,
    "fuel": "Petrol",
    "mileage": "24.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Power Steering",
      "ABS",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "61",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2021,
    "price": 1138332,
    "originalPrice": 1192850,
    "fuel": "Electric",
    "mileage": "21.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "AC",
      "Power Steering",
      "ABS",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "62",
    "make": "BMW",
    "model": "C-Class",
    "year": 2015,
    "price": 1415471,
    "originalPrice": 1540058,
    "fuel": "Electric",
    "mileage": "23.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "ABS",
      "Sunroof",
      "Power Steering",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "63",
    "make": "Audi",
    "model": "Civic",
    "year": 2015,
    "price": 746502,
    "originalPrice": 891142,
    "fuel": "Hybrid",
    "mileage": "19.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Power Steering",
      "Leather Seats",
      "ABS",
      "Airbags",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "64",
    "make": "Audi",
    "model": "C-Class",
    "year": 2011,
    "price": 1056520,
    "originalPrice": 1225316,
    "fuel": "Diesel",
    "mileage": "18.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Airbags",
      "Navigation",
      "AC",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "65",
    "make": "Honda",
    "model": "C-Class",
    "year": 2021,
    "price": 1313800,
    "originalPrice": 1482706,
    "fuel": "Electric",
    "mileage": "11.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "AC",
      "Airbags",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "66",
    "make": "Honda",
    "model": "C-Class",
    "year": 2019,
    "price": 723143,
    "originalPrice": 899307,
    "fuel": "Petrol",
    "mileage": "14.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "AC",
      "ABS",
      "Bluetooth",
      "Airbags",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "67",
    "make": "Audi",
    "model": "Elantra",
    "year": 2012,
    "price": 577907,
    "originalPrice": 751047,
    "fuel": "Electric",
    "mileage": "20.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "Power Steering",
      "Sunroof",
      "Bluetooth",
      "AC",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "68",
    "make": "Honda",
    "model": "Corolla",
    "year": 2019,
    "price": 873396,
    "originalPrice": 1065059,
    "fuel": "Electric",
    "mileage": "17.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Sunroof",
      "AC",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "69",
    "make": "Kia",
    "model": "Elantra",
    "year": 2023,
    "price": 817050,
    "originalPrice": 833984,
    "fuel": "Diesel",
    "mileage": "15.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "ABS",
      "Bluetooth",
      "AC"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "70",
    "make": "Ford",
    "model": "Corolla",
    "year": 2024,
    "price": 1250250,
    "originalPrice": 1282538,
    "fuel": "Petrol",
    "mileage": "21.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Navigation",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "71",
    "make": "Audi",
    "model": "Corolla",
    "year": 2019,
    "price": 660959,
    "originalPrice": 702128,
    "fuel": "Hybrid",
    "mileage": "14.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Bluetooth",
      "Navigation",
      "Airbags",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "72",
    "make": "Chevrolet",
    "model": "C-Class",
    "year": 2020,
    "price": 665223,
    "originalPrice": 848685,
    "fuel": "Diesel",
    "mileage": "18.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "ABS",
      "Sunroof",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "73",
    "make": "Honda",
    "model": "C-Class",
    "year": 2016,
    "price": 1339478,
    "originalPrice": 1536762,
    "fuel": "Diesel",
    "mileage": "11.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "AC",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "74",
    "make": "BMW",
    "model": "Elantra",
    "year": 2020,
    "price": 620726,
    "originalPrice": 687081,
    "fuel": "Hybrid",
    "mileage": "16.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "AC",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "75",
    "make": "Tesla",
    "model": "Elantra",
    "year": 2010,
    "price": 868933,
    "originalPrice": 965267,
    "fuel": "Diesel",
    "mileage": "15.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Sunroof",
      "Power Steering",
      "ABS",
      "AC",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "76",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2024,
    "price": 1323337,
    "originalPrice": 1427517,
    "fuel": "Electric",
    "mileage": "24.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Navigation",
      "Sunroof",
      "AC",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "77",
    "make": "Audi",
    "model": "Elantra",
    "year": 2020,
    "price": 1302958,
    "originalPrice": 1457175,
    "fuel": "Petrol",
    "mileage": "21.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "Airbags",
      "AC",
      "Power Steering",
      "ABS",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "78",
    "make": "Ford",
    "model": "X5",
    "year": 2017,
    "price": 1421516,
    "originalPrice": 1461464,
    "fuel": "Electric",
    "mileage": "14.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "79",
    "make": "Audi",
    "model": "Elantra",
    "year": 2013,
    "price": 1326819,
    "originalPrice": 1390256,
    "fuel": "Hybrid",
    "mileage": "11.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Power Steering",
      "Bluetooth",
      "Navigation",
      "AC"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "80",
    "make": "Ford",
    "model": "Model 3",
    "year": 2021,
    "price": 1133626,
    "originalPrice": 1298660,
    "fuel": "Diesel",
    "mileage": "14.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "ABS",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "81",
    "make": "BMW",
    "model": "Mustang",
    "year": 2012,
    "price": 1470707,
    "originalPrice": 1589194,
    "fuel": "Petrol",
    "mileage": "14.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Airbags",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "82",
    "make": "BMW",
    "model": "Q7",
    "year": 2016,
    "price": 1104324,
    "originalPrice": 1301684,
    "fuel": "Petrol",
    "mileage": "17.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Power Steering",
      "Airbags",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "83",
    "make": "Ford",
    "model": "Corolla",
    "year": 2013,
    "price": 1441206,
    "originalPrice": 1545687,
    "fuel": "Hybrid",
    "mileage": "22.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Power Steering",
      "Airbags",
      "Navigation",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "84",
    "make": "Honda",
    "model": "Mustang",
    "year": 2018,
    "price": 1499158,
    "originalPrice": 1519370,
    "fuel": "Hybrid",
    "mileage": "14.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "ABS",
      "Airbags",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "85",
    "make": "BMW",
    "model": "Q7",
    "year": 2014,
    "price": 663768,
    "originalPrice": 839845,
    "fuel": "Electric",
    "mileage": "20.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "Sunroof",
      "AC",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "86",
    "make": "Tesla",
    "model": "C-Class",
    "year": 2021,
    "price": 912836,
    "originalPrice": 944184,
    "fuel": "Hybrid",
    "mileage": "21.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Leather Seats",
      "Airbags",
      "Navigation",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "87",
    "make": "Ford",
    "model": "Civic",
    "year": 2021,
    "price": 505358,
    "originalPrice": 548479,
    "fuel": "Diesel",
    "mileage": "12.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "ABS",
      "AC",
      "Bluetooth",
      "Navigation",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "88",
    "make": "Tesla",
    "model": "Q7",
    "year": 2024,
    "price": 1343229,
    "originalPrice": 1489396,
    "fuel": "Diesel",
    "mileage": "16.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Bluetooth",
      "Navigation",
      "Airbags",
      "Sunroof",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "89",
    "make": "Ford",
    "model": "Malibu",
    "year": 2018,
    "price": 1281870,
    "originalPrice": 1380983,
    "fuel": "Diesel",
    "mileage": "23.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Airbags",
      "Leather Seats",
      "Sunroof",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "90",
    "make": "Audi",
    "model": "Elantra",
    "year": 2012,
    "price": 653965,
    "originalPrice": 800945,
    "fuel": "Diesel",
    "mileage": "24.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Power Steering",
      "Bluetooth",
      "AC",
      "ABS",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "91",
    "make": "Chevrolet",
    "model": "Model 3",
    "year": 2022,
    "price": 657799,
    "originalPrice": 741167,
    "fuel": "Petrol",
    "mileage": "14.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Bluetooth",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "92",
    "make": "Hyundai",
    "model": "Malibu",
    "year": 2019,
    "price": 546721,
    "originalPrice": 603702,
    "fuel": "Petrol",
    "mileage": "20.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Sunroof",
      "AC",
      "Power Steering",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "93",
    "make": "BMW",
    "model": "Elantra",
    "year": 2011,
    "price": 866920,
    "originalPrice": 885693,
    "fuel": "Diesel",
    "mileage": "17.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Power Steering",
      "Navigation",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "94",
    "make": "BMW",
    "model": "Q7",
    "year": 2013,
    "price": 1419721,
    "originalPrice": 1610046,
    "fuel": "Hybrid",
    "mileage": "11.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Leather Seats",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "95",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2023,
    "price": 1369081,
    "originalPrice": 1565713,
    "fuel": "Diesel",
    "mileage": "23.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "ABS",
      "Leather Seats",
      "Sunroof",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "96",
    "make": "BMW",
    "model": "Elantra",
    "year": 2013,
    "price": 727656,
    "originalPrice": 833240,
    "fuel": "Electric",
    "mileage": "24.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "97",
    "make": "Chevrolet",
    "model": "X5",
    "year": 2017,
    "price": 764564,
    "originalPrice": 797043,
    "fuel": "Diesel",
    "mileage": "21.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "98",
    "make": "Toyota",
    "model": "Sportage",
    "year": 2013,
    "price": 926190,
    "originalPrice": 1034089,
    "fuel": "Hybrid",
    "mileage": "21.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Power Steering",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "99",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2016,
    "price": 1452189,
    "originalPrice": 1489170,
    "fuel": "Petrol",
    "mileage": "14.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Sunroof",
      "AC",
      "Airbags",
      "ABS",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "100",
    "make": "Tesla",
    "model": "Elantra",
    "year": 2023,
    "price": 716930,
    "originalPrice": 814128,
    "fuel": "Diesel",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Bluetooth",
      "AC",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  }
];