export const cars = [
  {
    id: "1",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    price: 1350000,
    originalPrice: 1500000,
    fuel: "Petrol",
    mileage: "18 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Toyota+Corolla",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: true,
    isNewArrival: false,
    features: ["Airbags", "ABS", "Power Steering", "AC"],
    seating: 5,
    transmission: "Manual",
    category: "Sedan",
  },
  {
    id: "2",
    make: "Honda",
    model: "Civic",
    year: 2023,
    price: 1800000,
    originalPrice: null,
    fuel: "Diesel",
    mileage: "20 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Honda+Civic",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Touchscreen", "Cruise Control"],
    seating: 5,
    transmission: "Automatic",
    category: "Sedan",
  },
  {
    id: "3",
    make: "Hyundai",
    model: "i20",
    year: 2021,
    price: 950000,
    originalPrice: 1000000,
    fuel: "Petrol",
    mileage: "21 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Hyundai+i20",
    seasonalOffer: true,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: false,
    features: ["Airbags", "ABS", "Wireless Charging", "Blue Link"],
    seating: 5,
    transmission: "Manual",
    category: "Hatchback",
  },
  {
    id: "4",
    make: "Maruti Suzuki",
    model: "Swift",
    year: 2022,
    price: 750000,
    originalPrice: 850000,
    fuel: "Petrol",
    mileage: "22 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Maruti+Swift",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: false,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Power Steering", "AC"],
    seating: 5,
    transmission: "Manual",
    category: "Hatchback",
  },
  {
    id: "5",
    make: "Kia",
    model: "Seltos",
    year: 2023,
    price: 1600000,
    originalPrice: 1700000,
    fuel: "Diesel",
    mileage: "19 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Kia+Seltos",
    seasonalOffer: true,
    dealerPromotion: true,
    isHotDeal: true,
    isNewArrival: true,
    features: ["UVO Connect", "360° Camera", "Ambient Lighting", "Bose Audio"],
    seating: 5,
    transmission: "Automatic",
    category: "SUV",
  },
  {
    id: "6",
    make: "Tata",
    model: "Nexon",
    year: 2024,
    price: 1450000,
    originalPrice: null,
    fuel: "Petrol",
    mileage: "17 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Tata+Nexon",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
    features: ["5-Star Safety", "Harman Audio", "iRA App", "Touchscreen"],
    seating: 5,
    transmission: "Manual",
    category: "SUV",
  },
  {
    id: "7",
    make: "Toyota",
    model: "Innova",
    year: 2022,
    price: 2400000,
    originalPrice: 2500000,
    fuel: "Diesel",
    mileage: "14 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Toyota+Innova",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: false,
    isNewArrival: false,
    features: ["Airbags", "ABS", "Touchscreen", "Rear AC Vents"],
    seating: 7,
    transmission: "Manual",
    category: "MPV",
  },
  {
    id: "8",
    make: "Honda",
    model: "City",
    year: 2024,
    price: 1350000,
    originalPrice: 1500000,
    fuel: "Petrol",
    mileage: "17.8 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Honda+City",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: true,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Honda Sensing", "Sunroof"],
    seating: 5,
    transmission: "CVT",
    category: "Sedan",
  },
  {
    id: "9",
    make: "Hyundai",
    model: "Creta",
    year: 2023,
    price: 1400000,
    originalPrice: null,
    fuel: "Petrol",
    mileage: "17.4 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Hyundai+Creta",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Panoramic Sunroof", "360° Camera"],
    seating: 5,
    transmission: "Automatic",
    category: "SUV",
  },
  {
    id: "10",
    make: "Maruti Suzuki",
    model: "Baleno",
    year: 2023,
    price: 800000,
    originalPrice: 850000,
    fuel: "Petrol",
    mileage: "22.5 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Maruti+Baleno",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: false,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Touchscreen", "Reverse Camera"],
    seating: 5,
    transmission: "Automatic",
    category: "Hatchback",
  },
  {
    id: "11",
    make: "Kia",
    model: "Sonet",
    year: 2024,
    price: 1050000,
    originalPrice: null,
    fuel: "Petrol",
    mileage: "18.4 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Kia+Sonet",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: false,
    features: ["UVO Connect", "ABS", "Ventilated Seats", "Bose Audio"],
    seating: 5,
    transmission: "Manual",
    category: "SUV",
  },
  {
    id: "12",
    make: "Tata",
    model: "Harrier",
    year: 2024,
    price: 2200000,
    originalPrice: 2400000,
    fuel: "Diesel",
    mileage: "16 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Tata+Harrier",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: true,
    isNewArrival: false,
    features: ["5-Star Safety", "Panoramic Sunroof", "Harman Audio", "Cruise Control"],
    seating: 5,
    transmission: "Automatic",
    category: "SUV",
  },
  {
    id: "13",
    make: "Honda",
    model: "Jazz",
    year: 2023,
    price: 900000,
    originalPrice: 950000,
    fuel: "Petrol",
    mileage: "19 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Honda+Jazz",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Touchscreen", "Rear AC Vents"],
    seating: 5,
    transmission: "Manual",
    category: "Hatchback",
  },
  {
    id: "14",
    make: "Hyundai",
    model: "Verna",
    year: 2024,
    price: 1200000,
    originalPrice: 1300000,
    fuel: "Diesel",
    mileage: "21 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Hyundai+Verna",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: true,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Touchscreen", "LED Lights"],
    seating: 5,
    transmission: "Automatic",
    category: "Sedan",
  },
  {
    id: "15",
    make: "Maruti Suzuki",
    model: "Dzire",
    year: 2024,
    price: 850000,
    originalPrice: null,
    fuel: "Petrol",
    mileage: "24.1 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Maruti+Dzire",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Power Windows", "Central Locking"],
    seating: 5,
    transmission: "Manual",
    category: "Sedan",
  },
  {
    id: "16",
    make: "Kia",
    model: "Seltos",
    year: 2024,
    price: 1500000,
    originalPrice: 1600000,
    fuel: "Petrol",
    mileage: "16.8 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Kia+Seltos",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: false,
    isNewArrival: true,
    features: ["UVO Connect", "360° Camera", "Ambient Lighting", "Bose Audio"],
    seating: 5,
    transmission: "Automatic",
    category: "SUV",
  },
  {
    id: "17",
    make: "Mahindra",
    model: "Scorpio-N",
    year: 2024,
    price: 1600000,
    originalPrice: 1750000,
    fuel: "Diesel",
    mileage: "15.2 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Mahindra+Scorpio",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
    features: ["4WD", "ABS", "AdrenoX", "Captain Chairs"],
    seating: 7,
    transmission: "Manual",
    category: "SUV",
  },
  {
    id: "18",
    make: "Hyundai",
    model: "Venue",
    year: 2024,
    price: 950000,
    originalPrice: 1000000,
    fuel: "Petrol",
    mileage: "18.15 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Hyundai+Venue",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: true,
    isNewArrival: false,
    features: ["Airbags", "ABS", "Wireless Charging", "Blue Link"],
    seating: 5,
    transmission: "Manual",
    category: "SUV",
  },
  {
    id: "19",
    make: "MG",
    model: "Astor",
    year: 2024,
    price: 1400000,
    originalPrice: null,
    fuel: "Petrol",
    mileage: "17.22 km/l",
    image: "https://via.placeholder.com/300x200.png?text=MG+Astor",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
    features: ["AI Assistant", "ABS", "Panoramic Sunroof", "Level 2 ADAS"],
    seating: 5,
    transmission: "CVT",
    category: "SUV",
  },
  {
    id: "20",
    make: "Nissan",
    model: "Magnite",
    year: 2024,
    price: 850000,
    originalPrice: 900000,
    fuel: "Petrol",
    mileage: "18.75 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Nissan+Magnite",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: false,
    isNewArrival: true,
    features: ["Airbags", "ABS", "Around View Monitor", "JBL Audio"],
    seating: 5,
    transmission: "CVT",
    category: "SUV",
  },
];
