export const cars = [
  {
    id: "1",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    price: 1350000,
    originalPrice: 1500000,
    fuel: "Petrol",
    mileage: "18 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Toyota+Corolla",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: "2",
    make: "Honda",
    model: "Civic",
    year: 2023,
    price: 1800000,
    fuel: "Diesel",
    mileage: "20 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Honda+Civic",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    id: "3",
    make: "Hyundai",
    model: "i20",
    year: 2021,
    price: 950000,
    originalPrice: 1000000,
    fuel: "Petrol",
    mileage: "21 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Hyundai+i20",
    seasonalOffer: true,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    id: "4",
    make: "Maruti",
    model: "Swift",
    year: 2022,
    price: 750000,
    fuel: "Petrol",
    mileage: "22 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Maruti+Swift",
    seasonalOffer: false,
    dealerPromotion: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    id: "5",
    make: "Kia",
    model: "Seltos",
    year: 2023,
    price: 1600000,
    originalPrice: 1700000,
    fuel: "Diesel",
    mileage: "19 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Kia+Seltos",
    seasonalOffer: true,
    dealerPromotion: true,
    isHotDeal: true,
    isNewArrival: true,
  },
  {
    id: "6",
    make: "Tata",
    model: "Nexon",
    year: 2024,
    price: 1450000,
    fuel: "Petrol",
    mileage: "17 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Tata+Nexon",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    id: "7",
    make: "Skoda",
    model: "Rapid",
    year: 2021,
    price: 1100000,
    originalPrice: 1250000,
    fuel: "Petrol",
    mileage: "16 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Skoda+Rapid",
    seasonalOffer: true,
    dealerPromotion: false,
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: "8",
    make: "Volkswagen",
    model: "Polo",
    year: 2022,
    price: 900000,
    fuel: "Petrol",
    mileage: "18 km/l",
    image: "https://via.placeholder.com/300x200.png?text=VW+Polo",
    seasonalOffer: false,
    dealerPromotion: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    id: "9",
    make: "Mahindra",
    model: "XUV700",
    year: 2024,
    price: 2100000,
    originalPrice: 2250000,
    fuel: "Diesel",
    mileage: "15 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Mahindra+XUV700",
    seasonalOffer: true,
    dealerPromotion: true,
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: "10",
    make: "Renault",
    model: "Kiger",
    year: 2023,
    price: 800000,
    fuel: "Petrol",
    mileage: "19 km/l",
    image: "https://via.placeholder.com/300x200.png?text=Renault+Kiger",
    seasonalOffer: false,
    dealerPromotion: true,
    isHotDeal: false,
    isNewArrival: false,
  },
];
