export const DUMMY_CARS = [
  {
    "id": "1",
    "make": "Kia",
    "model": "Q7",
    "year": 2013,
    "price": 1043185,
    "originalPrice": 1066910,
    "fuel": "Hybrid",
    "mileage": "22.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "2",
    "make": "Kia",
    "model": "Civic",
    "year": 2015,
    "price": 1461479,
    "originalPrice": 1641398,
    "fuel": "Diesel",
    "mileage": "21.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Bluetooth",
      "Power Steering",
      "AC"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "3",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2010,
    "price": 1469778,
    "originalPrice": 1531359,
    "fuel": "Hybrid",
    "mileage": "10.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "ABS",
      "Sunroof",
      "Power Steering",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "4",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2014,
    "price": 921111,
    "originalPrice": 929506,
    "fuel": "Hybrid",
    "mileage": "19.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "5",
    "make": "BMW",
    "model": "Sportage",
    "year": 2010,
    "price": 1162140,
    "originalPrice": 1168715,
    "fuel": "Diesel",
    "mileage": "10.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Airbags",
      "Navigation",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "6",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2021,
    "price": 1060419,
    "originalPrice": 1119829,
    "fuel": "Electric",
    "mileage": "19.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Navigation",
      "Airbags",
      "Leather Seats",
      "Bluetooth",
      "ABS",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "7",
    "make": "BMW",
    "model": "Malibu",
    "year": 2017,
    "price": 1400231,
    "originalPrice": 1419001,
    "fuel": "Hybrid",
    "mileage": "14.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "ABS",
      "Sunroof",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "8",
    "make": "Honda",
    "model": "Corolla",
    "year": 2016,
    "price": 1498865,
    "originalPrice": 1622884,
    "fuel": "Petrol",
    "mileage": "17.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Airbags",
      "Sunroof",
      "Navigation",
      "Bluetooth",
      "AC"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "9",
    "make": "Toyota",
    "model": "Mustang",
    "year": 2022,
    "price": 1328894,
    "originalPrice": 1508101,
    "fuel": "Electric",
    "mileage": "18.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "10",
    "make": "Tesla",
    "model": "Civic",
    "year": 2023,
    "price": 586301,
    "originalPrice": 769652,
    "fuel": "Electric",
    "mileage": "13.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "AC",
      "Sunroof",
      "ABS",
      "Airbags",
      "Bluetooth",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "11",
    "make": "Mercedes",
    "model": "Civic",
    "year": 2010,
    "price": 1329181,
    "originalPrice": 1390594,
    "fuel": "Electric",
    "mileage": "25.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "AC",
      "ABS",
      "Airbags",
      "Power Steering",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "12",
    "make": "BMW",
    "model": "Model 3",
    "year": 2020,
    "price": 1031472,
    "originalPrice": 1054418,
    "fuel": "Hybrid",
    "mileage": "11.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "13",
    "make": "Honda",
    "model": "X5",
    "year": 2014,
    "price": 517488,
    "originalPrice": 694533,
    "fuel": "Electric",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "AC",
      "Leather Seats"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "14",
    "make": "Toyota",
    "model": "Corolla",
    "year": 2015,
    "price": 1353924,
    "originalPrice": 1545238,
    "fuel": "Petrol",
    "mileage": "15.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "ABS",
      "Sunroof",
      "AC",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "15",
    "make": "Kia",
    "model": "C-Class",
    "year": 2017,
    "price": 1389309,
    "originalPrice": 1438090,
    "fuel": "Petrol",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "ABS",
      "Navigation",
      "Leather Seats",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "16",
    "make": "Tesla",
    "model": "Sportage",
    "year": 2012,
    "price": 881626,
    "originalPrice": 892600,
    "fuel": "Diesel",
    "mileage": "16.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "ABS",
      "AC",
      "Leather Seats",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "17",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2016,
    "price": 1367226,
    "originalPrice": 1518207,
    "fuel": "Electric",
    "mileage": "24.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "18",
    "make": "Audi",
    "model": "Sportage",
    "year": 2014,
    "price": 774606,
    "originalPrice": 943270,
    "fuel": "Electric",
    "mileage": "16.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "19",
    "make": "Kia",
    "model": "Sportage",
    "year": 2016,
    "price": 657384,
    "originalPrice": 783657,
    "fuel": "Diesel",
    "mileage": "24.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "ABS",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "20",
    "make": "Chevrolet",
    "model": "X5",
    "year": 2013,
    "price": 859192,
    "originalPrice": 938329,
    "fuel": "Electric",
    "mileage": "12.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "Leather Seats",
      "Power Steering",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "21",
    "make": "BMW",
    "model": "Mustang",
    "year": 2011,
    "price": 708541,
    "originalPrice": 855564,
    "fuel": "Electric",
    "mileage": "24.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "22",
    "make": "Tesla",
    "model": "Sportage",
    "year": 2017,
    "price": 1056053,
    "originalPrice": 1173937,
    "fuel": "Hybrid",
    "mileage": "12.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Sunroof",
      "Power Steering",
      "ABS",
      "Leather Seats"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "23",
    "make": "Audi",
    "model": "Model 3",
    "year": 2015,
    "price": 1298202,
    "originalPrice": 1466485,
    "fuel": "Electric",
    "mileage": "24.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "Power Steering",
      "ABS",
      "AC",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "24",
    "make": "Toyota",
    "model": "C-Class",
    "year": 2010,
    "price": 1030359,
    "originalPrice": 1173211,
    "fuel": "Petrol",
    "mileage": "15.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "AC",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "25",
    "make": "Hyundai",
    "model": "Civic",
    "year": 2024,
    "price": 636152,
    "originalPrice": 756340,
    "fuel": "Diesel",
    "mileage": "20.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Navigation",
      "Leather Seats",
      "Power Steering",
      "Airbags",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "26",
    "make": "Hyundai",
    "model": "Elantra",
    "year": 2016,
    "price": 1038066,
    "originalPrice": 1149748,
    "fuel": "Petrol",
    "mileage": "24.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "AC",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "27",
    "make": "Audi",
    "model": "Model 3",
    "year": 2023,
    "price": 1032596,
    "originalPrice": 1227556,
    "fuel": "Hybrid",
    "mileage": "24.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "28",
    "make": "BMW",
    "model": "Malibu",
    "year": 2021,
    "price": 897964,
    "originalPrice": 949145,
    "fuel": "Electric",
    "mileage": "19.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "29",
    "make": "Honda",
    "model": "Sportage",
    "year": 2024,
    "price": 1434194,
    "originalPrice": 1558525,
    "fuel": "Electric",
    "mileage": "18.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Airbags",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "30",
    "make": "Hyundai",
    "model": "Malibu",
    "year": 2010,
    "price": 634638,
    "originalPrice": 682077,
    "fuel": "Petrol",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Leather Seats",
      "Power Steering",
      "Sunroof",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "31",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2011,
    "price": 1366841,
    "originalPrice": 1367160,
    "fuel": "Hybrid",
    "mileage": "18.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "AC",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "32",
    "make": "Audi",
    "model": "Mustang",
    "year": 2021,
    "price": 685839,
    "originalPrice": 700050,
    "fuel": "Hybrid",
    "mileage": "21.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "Bluetooth",
      "Power Steering",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "33",
    "make": "Hyundai",
    "model": "C-Class",
    "year": 2019,
    "price": 758081,
    "originalPrice": 797357,
    "fuel": "Electric",
    "mileage": "19.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "AC",
      "Navigation",
      "ABS",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "34",
    "make": "Chevrolet",
    "model": "Malibu",
    "year": 2022,
    "price": 763525,
    "originalPrice": 781743,
    "fuel": "Petrol",
    "mileage": "15.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "35",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2014,
    "price": 1186964,
    "originalPrice": 1218392,
    "fuel": "Petrol",
    "mileage": "18.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "Navigation",
      "ABS",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "36",
    "make": "Honda",
    "model": "Q7",
    "year": 2010,
    "price": 1331558,
    "originalPrice": 1473001,
    "fuel": "Petrol",
    "mileage": "15.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "AC",
      "Power Steering",
      "Navigation",
      "Sunroof",
      "Leather Seats",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "37",
    "make": "Chevrolet",
    "model": "Civic",
    "year": 2017,
    "price": 1391098,
    "originalPrice": 1525287,
    "fuel": "Electric",
    "mileage": "19.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "38",
    "make": "Audi",
    "model": "Sportage",
    "year": 2018,
    "price": 1381943,
    "originalPrice": 1433708,
    "fuel": "Petrol",
    "mileage": "21.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Sunroof",
      "Leather Seats",
      "ABS",
      "Airbags",
      "AC",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "39",
    "make": "Mercedes",
    "model": "Civic",
    "year": 2022,
    "price": 1122463,
    "originalPrice": 1319233,
    "fuel": "Hybrid",
    "mileage": "11.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Sunroof",
      "Leather Seats",
      "ABS",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "40",
    "make": "Hyundai",
    "model": "Malibu",
    "year": 2022,
    "price": 501961,
    "originalPrice": 513470,
    "fuel": "Electric",
    "mileage": "17.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Bluetooth",
      "ABS",
      "Navigation",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "41",
    "make": "Tesla",
    "model": "Sportage",
    "year": 2020,
    "price": 1228794,
    "originalPrice": 1271283,
    "fuel": "Diesel",
    "mileage": "24.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "42",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2013,
    "price": 678636,
    "originalPrice": 826517,
    "fuel": "Petrol",
    "mileage": "24.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Airbags",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "43",
    "make": "Kia",
    "model": "Elantra",
    "year": 2019,
    "price": 894296,
    "originalPrice": 942032,
    "fuel": "Petrol",
    "mileage": "19.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Bluetooth",
      "Airbags",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "44",
    "make": "Ford",
    "model": "X5",
    "year": 2015,
    "price": 1149902,
    "originalPrice": 1198837,
    "fuel": "Petrol",
    "mileage": "19.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Sunroof",
      "AC",
      "Airbags",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "45",
    "make": "Hyundai",
    "model": "Civic",
    "year": 2016,
    "price": 1132918,
    "originalPrice": 1226490,
    "fuel": "Electric",
    "mileage": "16.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Power Steering",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "46",
    "make": "Kia",
    "model": "Elantra",
    "year": 2013,
    "price": 800605,
    "originalPrice": 813418,
    "fuel": "Hybrid",
    "mileage": "18.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Leather Seats",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "47",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2015,
    "price": 1381148,
    "originalPrice": 1403640,
    "fuel": "Hybrid",
    "mileage": "21.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Leather Seats",
      "AC",
      "Sunroof",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "48",
    "make": "Kia",
    "model": "Civic",
    "year": 2011,
    "price": 835426,
    "originalPrice": 903727,
    "fuel": "Hybrid",
    "mileage": "17.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Leather Seats",
      "Navigation",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "49",
    "make": "Toyota",
    "model": "Q7",
    "year": 2016,
    "price": 1277234,
    "originalPrice": 1424503,
    "fuel": "Hybrid",
    "mileage": "18.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "AC",
      "Power Steering",
      "Leather Seats",
      "Navigation",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "50",
    "make": "Audi",
    "model": "Corolla",
    "year": 2021,
    "price": 821961,
    "originalPrice": 1010372,
    "fuel": "Petrol",
    "mileage": "12.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Airbags",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "51",
    "make": "Mercedes",
    "model": "X5",
    "year": 2018,
    "price": 528108,
    "originalPrice": 703542,
    "fuel": "Electric",
    "mileage": "18.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Sunroof",
      "Airbags",
      "Leather Seats",
      "Navigation",
      "Bluetooth"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "52",
    "make": "Ford",
    "model": "Model 3",
    "year": 2018,
    "price": 690982,
    "originalPrice": 854622,
    "fuel": "Diesel",
    "mileage": "18.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "53",
    "make": "Ford",
    "model": "Civic",
    "year": 2022,
    "price": 1276019,
    "originalPrice": 1455348,
    "fuel": "Electric",
    "mileage": "15.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Leather Seats",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "54",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2015,
    "price": 540414,
    "originalPrice": 576649,
    "fuel": "Electric",
    "mileage": "19.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "ABS",
      "Bluetooth",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "55",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2023,
    "price": 1271728,
    "originalPrice": 1321138,
    "fuel": "Electric",
    "mileage": "23.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "56",
    "make": "Mercedes",
    "model": "Q7",
    "year": 2013,
    "price": 729106,
    "originalPrice": 877399,
    "fuel": "Petrol",
    "mileage": "18.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "57",
    "make": "Ford",
    "model": "Sportage",
    "year": 2023,
    "price": 793021,
    "originalPrice": 853549,
    "fuel": "Petrol",
    "mileage": "19.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Leather Seats",
      "Airbags",
      "AC"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "58",
    "make": "Kia",
    "model": "C-Class",
    "year": 2019,
    "price": 611896,
    "originalPrice": 705684,
    "fuel": "Electric",
    "mileage": "14.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "59",
    "make": "Audi",
    "model": "Sportage",
    "year": 2018,
    "price": 541265,
    "originalPrice": 734179,
    "fuel": "Diesel",
    "mileage": "20.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "Sunroof",
      "Bluetooth",
      "Navigation",
      "Airbags",
      "ABS",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "60",
    "make": "Kia",
    "model": "Mustang",
    "year": 2012,
    "price": 1256365,
    "originalPrice": 1360760,
    "fuel": "Diesel",
    "mileage": "16.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "ABS",
      "Power Steering",
      "Leather Seats",
      "AC",
      "Bluetooth"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "61",
    "make": "Hyundai",
    "model": "Civic",
    "year": 2018,
    "price": 565114,
    "originalPrice": 763589,
    "fuel": "Diesel",
    "mileage": "14.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "Airbags",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "62",
    "make": "Hyundai",
    "model": "Model 3",
    "year": 2018,
    "price": 818830,
    "originalPrice": 911658,
    "fuel": "Electric",
    "mileage": "19.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Power Steering",
      "Bluetooth"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "63",
    "make": "Mercedes",
    "model": "Malibu",
    "year": 2013,
    "price": 695061,
    "originalPrice": 886359,
    "fuel": "Diesel",
    "mileage": "13.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Sunroof",
      "Power Steering",
      "Bluetooth",
      "Airbags",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "64",
    "make": "Tesla",
    "model": "Elantra",
    "year": 2023,
    "price": 1178239,
    "originalPrice": 1197831,
    "fuel": "Petrol",
    "mileage": "11.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "65",
    "make": "Kia",
    "model": "Civic",
    "year": 2021,
    "price": 547347,
    "originalPrice": 563601,
    "fuel": "Diesel",
    "mileage": "16.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Leather Seats",
      "ABS",
      "Bluetooth",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "66",
    "make": "Hyundai",
    "model": "Q7",
    "year": 2012,
    "price": 708793,
    "originalPrice": 890625,
    "fuel": "Electric",
    "mileage": "14.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Sunroof",
      "Navigation",
      "Airbags",
      "Power Steering",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "67",
    "make": "Audi",
    "model": "Civic",
    "year": 2021,
    "price": 1260748,
    "originalPrice": 1360329,
    "fuel": "Petrol",
    "mileage": "14.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "68",
    "make": "Toyota",
    "model": "Q7",
    "year": 2015,
    "price": 953919,
    "originalPrice": 972118,
    "fuel": "Petrol",
    "mileage": "12.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "Airbags",
      "AC",
      "Sunroof",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "69",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2016,
    "price": 849524,
    "originalPrice": 870956,
    "fuel": "Petrol",
    "mileage": "24.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Airbags",
      "ABS",
      "Power Steering",
      "Navigation",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "70",
    "make": "Ford",
    "model": "Elantra",
    "year": 2022,
    "price": 836662,
    "originalPrice": 1021208,
    "fuel": "Electric",
    "mileage": "22.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "Leather Seats",
      "Bluetooth",
      "ABS",
      "AC",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "71",
    "make": "BMW",
    "model": "Elantra",
    "year": 2024,
    "price": 1447709,
    "originalPrice": 1593646,
    "fuel": "Petrol",
    "mileage": "16.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "Navigation",
      "Power Steering",
      "Airbags",
      "AC"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "72",
    "make": "Tesla",
    "model": "C-Class",
    "year": 2024,
    "price": 720318,
    "originalPrice": 745161,
    "fuel": "Diesel",
    "mileage": "20.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "ABS",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "73",
    "make": "Audi",
    "model": "Malibu",
    "year": 2010,
    "price": 982855,
    "originalPrice": 992688,
    "fuel": "Electric",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "74",
    "make": "Kia",
    "model": "Civic",
    "year": 2016,
    "price": 995183,
    "originalPrice": 1054579,
    "fuel": "Hybrid",
    "mileage": "24.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Navigation",
      "ABS",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "75",
    "make": "Toyota",
    "model": "Elantra",
    "year": 2012,
    "price": 765311,
    "originalPrice": 806315,
    "fuel": "Diesel",
    "mileage": "20.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "Power Steering",
      "AC",
      "Bluetooth",
      "Navigation",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "76",
    "make": "Kia",
    "model": "C-Class",
    "year": 2018,
    "price": 1226351,
    "originalPrice": 1424586,
    "fuel": "Hybrid",
    "mileage": "15.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "AC",
      "Bluetooth",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "77",
    "make": "Tesla",
    "model": "Q7",
    "year": 2019,
    "price": 930648,
    "originalPrice": 1051017,
    "fuel": "Diesel",
    "mileage": "24.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "AC",
      "Sunroof",
      "Bluetooth",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "78",
    "make": "Toyota",
    "model": "Model 3",
    "year": 2018,
    "price": 1125943,
    "originalPrice": 1197202,
    "fuel": "Hybrid",
    "mileage": "20.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Power Steering",
      "Navigation",
      "AC",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "79",
    "make": "Toyota",
    "model": "Q7",
    "year": 2018,
    "price": 1337640,
    "originalPrice": 1412876,
    "fuel": "Diesel",
    "mileage": "17.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Sunroof",
      "Power Steering",
      "Bluetooth",
      "ABS",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "80",
    "make": "Ford",
    "model": "Elantra",
    "year": 2023,
    "price": 569672,
    "originalPrice": 670128,
    "fuel": "Petrol",
    "mileage": "16.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Navigation",
      "ABS",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "81",
    "make": "Audi",
    "model": "Model 3",
    "year": 2013,
    "price": 753464,
    "originalPrice": 943691,
    "fuel": "Electric",
    "mileage": "21.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Power Steering",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "82",
    "make": "Audi",
    "model": "X5",
    "year": 2014,
    "price": 838637,
    "originalPrice": 930093,
    "fuel": "Diesel",
    "mileage": "18.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "83",
    "make": "Ford",
    "model": "Civic",
    "year": 2010,
    "price": 559850,
    "originalPrice": 744372,
    "fuel": "Electric",
    "mileage": "12.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "AC",
      "Navigation",
      "Bluetooth",
      "ABS",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "84",
    "make": "Toyota",
    "model": "X5",
    "year": 2011,
    "price": 594732,
    "originalPrice": 706253,
    "fuel": "Petrol",
    "mileage": "18.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "85",
    "make": "Toyota",
    "model": "C-Class",
    "year": 2012,
    "price": 1159699,
    "originalPrice": 1162722,
    "fuel": "Hybrid",
    "mileage": "19.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "ABS",
      "Power Steering",
      "Navigation",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "86",
    "make": "Honda",
    "model": "Sportage",
    "year": 2022,
    "price": 1454196,
    "originalPrice": 1546891,
    "fuel": "Electric",
    "mileage": "13.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "ABS",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "87",
    "make": "Mercedes",
    "model": "Sportage",
    "year": 2022,
    "price": 1240810,
    "originalPrice": 1392895,
    "fuel": "Diesel",
    "mileage": "13.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Navigation",
      "Power Steering",
      "ABS",
      "Bluetooth"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "88",
    "make": "Hyundai",
    "model": "Malibu",
    "year": 2013,
    "price": 1099974,
    "originalPrice": 1279037,
    "fuel": "Petrol",
    "mileage": "24.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "89",
    "make": "Audi",
    "model": "Mustang",
    "year": 2015,
    "price": 761203,
    "originalPrice": 798367,
    "fuel": "Diesel",
    "mileage": "16.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "Bluetooth",
      "Navigation",
      "Sunroof",
      "AC",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "90",
    "make": "Ford",
    "model": "Sportage",
    "year": 2023,
    "price": 701446,
    "originalPrice": 807717,
    "fuel": "Electric",
    "mileage": "10.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Leather Seats",
      "Navigation",
      "Airbags",
      "AC",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "91",
    "make": "Chevrolet",
    "model": "Mustang",
    "year": 2018,
    "price": 562532,
    "originalPrice": 740866,
    "fuel": "Electric",
    "mileage": "13.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "Navigation",
      "ABS",
      "Leather Seats",
      "Power Steering",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "92",
    "make": "Toyota",
    "model": "Elantra",
    "year": 2023,
    "price": 1211305,
    "originalPrice": 1256953,
    "fuel": "Hybrid",
    "mileage": "16.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "AC",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "93",
    "make": "Hyundai",
    "model": "X5",
    "year": 2014,
    "price": 519413,
    "originalPrice": 699773,
    "fuel": "Electric",
    "mileage": "16.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "94",
    "make": "Hyundai",
    "model": "Elantra",
    "year": 2014,
    "price": 1386104,
    "originalPrice": 1573822,
    "fuel": "Petrol",
    "mileage": "23.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "ABS",
      "Airbags",
      "Navigation",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "95",
    "make": "Honda",
    "model": "Sportage",
    "year": 2019,
    "price": 812742,
    "originalPrice": 914802,
    "fuel": "Hybrid",
    "mileage": "24.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "ABS",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "96",
    "make": "Mercedes",
    "model": "Corolla",
    "year": 2011,
    "price": 1269765,
    "originalPrice": 1348234,
    "fuel": "Petrol",
    "mileage": "11.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Leather Seats",
      "Sunroof",
      "AC",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "97",
    "make": "Honda",
    "model": "Elantra",
    "year": 2011,
    "price": 1346763,
    "originalPrice": 1505194,
    "fuel": "Diesel",
    "mileage": "16.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Power Steering",
      "Airbags",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "98",
    "make": "BMW",
    "model": "Sportage",
    "year": 2012,
    "price": 871834,
    "originalPrice": 963933,
    "fuel": "Hybrid",
    "mileage": "13.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Navigation",
      "Power Steering",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "99",
    "make": "Hyundai",
    "model": "C-Class",
    "year": 2021,
    "price": 1092553,
    "originalPrice": 1233395,
    "fuel": "Petrol",
    "mileage": "23.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Leather Seats",
      "ABS",
      "AC"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "100",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2021,
    "price": 963920,
    "originalPrice": 991982,
    "fuel": "Diesel",
    "mileage": "17.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Sunroof",
      "Navigation",
      "Leather Seats",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  }
];