export const DUMMY_CARS = [
  {
    "id": "1",
    "make": "Audi",
    "model": "Elantra",
    "year": 2019,
    "price": 856507,
    "originalPrice": 1006117,
    "fuel": "Electric",
    "mileage": "13.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Navigation",
      "AC",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "2",
    "make": "Honda",
    "model": "Malibu",
    "year": 2015,
    "price": 1367711,
    "originalPrice": 1482330,
    "fuel": "Petrol",
    "mileage": "21.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "3",
    "make": "Hyundai",
    "model": "Civic",
    "year": 2021,
    "price": 1263990,
    "originalPrice": 1462779,
    "fuel": "Diesel",
    "mileage": "17.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "ABS",
      "AC",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "4",
    "make": "Kia",
    "model": "C-Class",
    "year": 2019,
    "price": 639708,
    "originalPrice": 796528,
    "fuel": "Diesel",
    "mileage": "16.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Sunroof",
      "AC"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "5",
    "make": "Toyota",
    "model": "Sportage",
    "year": 2013,
    "price": 821983,
    "originalPrice": 865090,
    "fuel": "Diesel",
    "mileage": "10.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "Leather Seats",
      "Sunroof",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "6",
    "make": "Tesla",
    "model": "Mustang",
    "year": 2014,
    "price": 1270093,
    "originalPrice": 1430099,
    "fuel": "Diesel",
    "mileage": "22.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Navigation",
      "Power Steering",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "7",
    "make": "Chevrolet",
    "model": "C-Class",
    "year": 2014,
    "price": 1399569,
    "originalPrice": 1535501,
    "fuel": "Diesel",
    "mileage": "16.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "Airbags",
      "Navigation",
      "Sunroof",
      "Power Steering",
      "Bluetooth"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "8",
    "make": "Hyundai",
    "model": "C-Class",
    "year": 2015,
    "price": 1071502,
    "originalPrice": 1103377,
    "fuel": "Petrol",
    "mileage": "22.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Leather Seats",
      "Power Steering",
      "AC"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "9",
    "make": "Kia",
    "model": "Model 3",
    "year": 2014,
    "price": 924461,
    "originalPrice": 1116610,
    "fuel": "Petrol",
    "mileage": "16.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Airbags",
      "Navigation"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "10",
    "make": "Hyundai",
    "model": "X5",
    "year": 2013,
    "price": 1002901,
    "originalPrice": 1123993,
    "fuel": "Diesel",
    "mileage": "12.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "11",
    "make": "Kia",
    "model": "X5",
    "year": 2021,
    "price": 1021153,
    "originalPrice": 1079432,
    "fuel": "Diesel",
    "mileage": "15.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "AC",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "12",
    "make": "Kia",
    "model": "Model 3",
    "year": 2014,
    "price": 1001144,
    "originalPrice": 1101852,
    "fuel": "Hybrid",
    "mileage": "10.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "13",
    "make": "BMW",
    "model": "Corolla",
    "year": 2014,
    "price": 842257,
    "originalPrice": 941100,
    "fuel": "Diesel",
    "mileage": "13.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "Navigation",
      "Bluetooth",
      "AC",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "14",
    "make": "Toyota",
    "model": "Sportage",
    "year": 2018,
    "price": 551864,
    "originalPrice": 601296,
    "fuel": "Electric",
    "mileage": "14.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "ABS",
      "Sunroof",
      "Power Steering",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "15",
    "make": "Ford",
    "model": "C-Class",
    "year": 2019,
    "price": 536021,
    "originalPrice": 682576,
    "fuel": "Hybrid",
    "mileage": "20.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Power Steering",
      "AC",
      "Sunroof",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "16",
    "make": "Toyota",
    "model": "Q7",
    "year": 2023,
    "price": 971145,
    "originalPrice": 1130054,
    "fuel": "Petrol",
    "mileage": "17.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "17",
    "make": "Audi",
    "model": "Malibu",
    "year": 2011,
    "price": 1013265,
    "originalPrice": 1116034,
    "fuel": "Electric",
    "mileage": "22.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "ABS",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "18",
    "make": "BMW",
    "model": "Elantra",
    "year": 2013,
    "price": 1271151,
    "originalPrice": 1467753,
    "fuel": "Electric",
    "mileage": "23.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "Power Steering",
      "ABS",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "19",
    "make": "BMW",
    "model": "Sportage",
    "year": 2018,
    "price": 731720,
    "originalPrice": 766282,
    "fuel": "Hybrid",
    "mileage": "14.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Leather Seats",
      "Bluetooth",
      "Sunroof",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "20",
    "make": "Ford",
    "model": "Corolla",
    "year": 2021,
    "price": 1006398,
    "originalPrice": 1008223,
    "fuel": "Hybrid",
    "mileage": "16.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Bluetooth",
      "AC",
      "Leather Seats",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "21",
    "make": "Honda",
    "model": "Elantra",
    "year": 2019,
    "price": 1138115,
    "originalPrice": 1217767,
    "fuel": "Electric",
    "mileage": "10.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "AC",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "22",
    "make": "Ford",
    "model": "Q7",
    "year": 2022,
    "price": 812891,
    "originalPrice": 863775,
    "fuel": "Diesel",
    "mileage": "11.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "Bluetooth",
      "AC",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "23",
    "make": "Mercedes",
    "model": "Mustang",
    "year": 2015,
    "price": 1478489,
    "originalPrice": 1507985,
    "fuel": "Diesel",
    "mileage": "18.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Airbags",
      "Power Steering",
      "Sunroof",
      "AC",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "24",
    "make": "Ford",
    "model": "Model 3",
    "year": 2022,
    "price": 1404908,
    "originalPrice": 1410003,
    "fuel": "Electric",
    "mileage": "23.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Navigation",
      "Airbags",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "25",
    "make": "Audi",
    "model": "Q7",
    "year": 2018,
    "price": 928913,
    "originalPrice": 1005954,
    "fuel": "Petrol",
    "mileage": "23.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "AC",
      "Power Steering",
      "Bluetooth",
      "Navigation",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "26",
    "make": "Tesla",
    "model": "Civic",
    "year": 2018,
    "price": 775068,
    "originalPrice": 857734,
    "fuel": "Diesel",
    "mileage": "24.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "27",
    "make": "Audi",
    "model": "Model 3",
    "year": 2017,
    "price": 1379649,
    "originalPrice": 1424140,
    "fuel": "Electric",
    "mileage": "15.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Sunroof",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "28",
    "make": "Hyundai",
    "model": "Corolla",
    "year": 2021,
    "price": 844393,
    "originalPrice": 1020407,
    "fuel": "Diesel",
    "mileage": "15.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Power Steering",
      "Sunroof",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "29",
    "make": "Ford",
    "model": "Elantra",
    "year": 2012,
    "price": 714056,
    "originalPrice": 842993,
    "fuel": "Electric",
    "mileage": "11.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "Power Steering",
      "ABS",
      "Sunroof",
      "Navigation",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "30",
    "make": "Hyundai",
    "model": "Sportage",
    "year": 2011,
    "price": 1174954,
    "originalPrice": 1242932,
    "fuel": "Petrol",
    "mileage": "13.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "Power Steering",
      "Sunroof",
      "AC",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "31",
    "make": "Tesla",
    "model": "Elantra",
    "year": 2023,
    "price": 780165,
    "originalPrice": 839066,
    "fuel": "Electric",
    "mileage": "16.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "ABS",
      "Navigation",
      "AC",
      "Leather Seats",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "32",
    "make": "Toyota",
    "model": "Civic",
    "year": 2011,
    "price": 1335690,
    "originalPrice": 1361183,
    "fuel": "Petrol",
    "mileage": "20.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Bluetooth",
      "AC",
      "Navigation",
      "ABS",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "33",
    "make": "Ford",
    "model": "Sportage",
    "year": 2013,
    "price": 1155671,
    "originalPrice": 1194546,
    "fuel": "Diesel",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "AC",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "34",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2021,
    "price": 1378695,
    "originalPrice": 1400472,
    "fuel": "Diesel",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "ABS",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "35",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2020,
    "price": 1225359,
    "originalPrice": 1384592,
    "fuel": "Hybrid",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "ABS",
      "Sunroof",
      "AC"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "36",
    "make": "Hyundai",
    "model": "Q7",
    "year": 2019,
    "price": 812495,
    "originalPrice": 840112,
    "fuel": "Diesel",
    "mileage": "11.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Leather Seats",
      "Navigation",
      "Sunroof",
      "Airbags",
      "AC",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "37",
    "make": "BMW",
    "model": "Model 3",
    "year": 2020,
    "price": 1392876,
    "originalPrice": 1470798,
    "fuel": "Diesel",
    "mileage": "10.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Navigation",
      "Leather Seats",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "38",
    "make": "Audi",
    "model": "Corolla",
    "year": 2024,
    "price": 1078166,
    "originalPrice": 1096230,
    "fuel": "Petrol",
    "mileage": "18.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "AC",
      "Power Steering",
      "ABS",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "39",
    "make": "Tesla",
    "model": "Elantra",
    "year": 2023,
    "price": 839004,
    "originalPrice": 976758,
    "fuel": "Electric",
    "mileage": "17.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Navigation",
      "AC"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "40",
    "make": "Audi",
    "model": "Sportage",
    "year": 2014,
    "price": 876022,
    "originalPrice": 945270,
    "fuel": "Petrol",
    "mileage": "13.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Bluetooth",
      "Sunroof",
      "Navigation"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "41",
    "make": "Toyota",
    "model": "C-Class",
    "year": 2019,
    "price": 691251,
    "originalPrice": 754373,
    "fuel": "Hybrid",
    "mileage": "24.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "Power Steering",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "42",
    "make": "Mercedes",
    "model": "Mustang",
    "year": 2018,
    "price": 1372203,
    "originalPrice": 1387799,
    "fuel": "Diesel",
    "mileage": "12.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "ABS",
      "Power Steering",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "43",
    "make": "Audi",
    "model": "Sportage",
    "year": 2017,
    "price": 561827,
    "originalPrice": 750480,
    "fuel": "Diesel",
    "mileage": "14.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Airbags",
      "Navigation",
      "Power Steering",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "44",
    "make": "BMW",
    "model": "Sportage",
    "year": 2024,
    "price": 621632,
    "originalPrice": 745620,
    "fuel": "Hybrid",
    "mileage": "23.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "Airbags",
      "Bluetooth",
      "AC"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "45",
    "make": "Mercedes",
    "model": "Malibu",
    "year": 2022,
    "price": 1316513,
    "originalPrice": 1323402,
    "fuel": "Diesel",
    "mileage": "24.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "46",
    "make": "Kia",
    "model": "Sportage",
    "year": 2024,
    "price": 1488277,
    "originalPrice": 1494995,
    "fuel": "Petrol",
    "mileage": "21.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Navigation",
      "Airbags",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "47",
    "make": "Hyundai",
    "model": "Elantra",
    "year": 2010,
    "price": 1264394,
    "originalPrice": 1289748,
    "fuel": "Hybrid",
    "mileage": "11.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Airbags",
      "AC",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "48",
    "make": "Hyundai",
    "model": "Corolla",
    "year": 2011,
    "price": 680831,
    "originalPrice": 747681,
    "fuel": "Electric",
    "mileage": "12.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Sunroof",
      "AC",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "49",
    "make": "BMW",
    "model": "C-Class",
    "year": 2019,
    "price": 1026942,
    "originalPrice": 1135320,
    "fuel": "Petrol",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Bluetooth",
      "ABS",
      "Navigation",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "50",
    "make": "Toyota",
    "model": "Civic",
    "year": 2022,
    "price": 1251429,
    "originalPrice": 1331850,
    "fuel": "Petrol",
    "mileage": "16.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "51",
    "make": "Mercedes",
    "model": "Mustang",
    "year": 2013,
    "price": 1251052,
    "originalPrice": 1428992,
    "fuel": "Electric",
    "mileage": "18.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "52",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2022,
    "price": 975455,
    "originalPrice": 1168229,
    "fuel": "Electric",
    "mileage": "20.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "Navigation",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "53",
    "make": "Chevrolet",
    "model": "X5",
    "year": 2010,
    "price": 1099175,
    "originalPrice": 1163534,
    "fuel": "Electric",
    "mileage": "18.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Bluetooth",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "54",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2016,
    "price": 820163,
    "originalPrice": 977302,
    "fuel": "Petrol",
    "mileage": "24.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Bluetooth",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "55",
    "make": "Mercedes",
    "model": "Q7",
    "year": 2020,
    "price": 1174391,
    "originalPrice": 1211318,
    "fuel": "Electric",
    "mileage": "19.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "56",
    "make": "Mercedes",
    "model": "X5",
    "year": 2024,
    "price": 1496193,
    "originalPrice": 1545464,
    "fuel": "Electric",
    "mileage": "15.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Navigation",
      "ABS",
      "Bluetooth",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "57",
    "make": "Hyundai",
    "model": "X5",
    "year": 2018,
    "price": 1069855,
    "originalPrice": 1116313,
    "fuel": "Petrol",
    "mileage": "24.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "ABS",
      "Leather Seats"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "58",
    "make": "Hyundai",
    "model": "Model 3",
    "year": 2012,
    "price": 1272988,
    "originalPrice": 1369430,
    "fuel": "Diesel",
    "mileage": "16.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Power Steering",
      "AC",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "59",
    "make": "Kia",
    "model": "Model 3",
    "year": 2016,
    "price": 1081418,
    "originalPrice": 1259093,
    "fuel": "Hybrid",
    "mileage": "10.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Airbags",
      "Power Steering",
      "AC"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "60",
    "make": "Ford",
    "model": "Sportage",
    "year": 2011,
    "price": 1086953,
    "originalPrice": 1125167,
    "fuel": "Electric",
    "mileage": "11.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Navigation",
      "Power Steering",
      "Bluetooth",
      "Airbags",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "61",
    "make": "Kia",
    "model": "Corolla",
    "year": 2018,
    "price": 1310670,
    "originalPrice": 1449504,
    "fuel": "Diesel",
    "mileage": "19.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "ABS",
      "Airbags",
      "Sunroof",
      "Bluetooth",
      "AC"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "62",
    "make": "Audi",
    "model": "X5",
    "year": 2012,
    "price": 1270956,
    "originalPrice": 1438893,
    "fuel": "Petrol",
    "mileage": "15.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "AC",
      "Leather Seats",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "63",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2018,
    "price": 976579,
    "originalPrice": 1078280,
    "fuel": "Diesel",
    "mileage": "13.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "AC",
      "Airbags",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "64",
    "make": "BMW",
    "model": "Sportage",
    "year": 2012,
    "price": 1461202,
    "originalPrice": 1609608,
    "fuel": "Diesel",
    "mileage": "21.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "ABS",
      "Power Steering",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "65",
    "make": "Kia",
    "model": "Elantra",
    "year": 2021,
    "price": 1364705,
    "originalPrice": 1494191,
    "fuel": "Electric",
    "mileage": "14.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "66",
    "make": "Ford",
    "model": "Sportage",
    "year": 2019,
    "price": 1450305,
    "originalPrice": 1516363,
    "fuel": "Diesel",
    "mileage": "22.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Leather Seats",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "67",
    "make": "Tesla",
    "model": "Sportage",
    "year": 2010,
    "price": 836547,
    "originalPrice": 853219,
    "fuel": "Petrol",
    "mileage": "11.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Power Steering",
      "Bluetooth",
      "Leather Seats",
      "AC",
      "ABS",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "68",
    "make": "Toyota",
    "model": "Model 3",
    "year": 2015,
    "price": 1455550,
    "originalPrice": 1570428,
    "fuel": "Petrol",
    "mileage": "10.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "69",
    "make": "Honda",
    "model": "Civic",
    "year": 2022,
    "price": 1373934,
    "originalPrice": 1415928,
    "fuel": "Electric",
    "mileage": "15.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Sunroof",
      "Leather Seats",
      "Bluetooth",
      "Navigation",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "70",
    "make": "Mercedes",
    "model": "Mustang",
    "year": 2019,
    "price": 845253,
    "originalPrice": 995300,
    "fuel": "Hybrid",
    "mileage": "20.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Airbags",
      "Power Steering",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "71",
    "make": "Ford",
    "model": "Corolla",
    "year": 2021,
    "price": 1275294,
    "originalPrice": 1375940,
    "fuel": "Petrol",
    "mileage": "20.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Leather Seats",
      "Sunroof",
      "Navigation",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "72",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2016,
    "price": 1417220,
    "originalPrice": 1566694,
    "fuel": "Diesel",
    "mileage": "18.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "Bluetooth",
      "AC",
      "Power Steering",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "73",
    "make": "Audi",
    "model": "Q7",
    "year": 2024,
    "price": 676583,
    "originalPrice": 873154,
    "fuel": "Petrol",
    "mileage": "18.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Navigation",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "74",
    "make": "Mercedes",
    "model": "Corolla",
    "year": 2020,
    "price": 932534,
    "originalPrice": 999648,
    "fuel": "Diesel",
    "mileage": "22.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "ABS",
      "Airbags",
      "Navigation",
      "Bluetooth",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "75",
    "make": "Tesla",
    "model": "Model 3",
    "year": 2024,
    "price": 1166768,
    "originalPrice": 1285802,
    "fuel": "Electric",
    "mileage": "10.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Bluetooth",
      "Power Steering",
      "Navigation",
      "AC",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "76",
    "make": "Audi",
    "model": "Model 3",
    "year": 2012,
    "price": 1109084,
    "originalPrice": 1249957,
    "fuel": "Petrol",
    "mileage": "11.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Airbags",
      "AC",
      "ABS",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "77",
    "make": "Honda",
    "model": "Mustang",
    "year": 2015,
    "price": 1092944,
    "originalPrice": 1121780,
    "fuel": "Electric",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Leather Seats",
      "ABS",
      "Airbags",
      "Bluetooth"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "78",
    "make": "Hyundai",
    "model": "Corolla",
    "year": 2021,
    "price": 877457,
    "originalPrice": 907354,
    "fuel": "Hybrid",
    "mileage": "21.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Airbags",
      "Power Steering",
      "ABS",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "79",
    "make": "Tesla",
    "model": "Civic",
    "year": 2021,
    "price": 594357,
    "originalPrice": 602625,
    "fuel": "Petrol",
    "mileage": "15.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Navigation",
      "Airbags",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "80",
    "make": "BMW",
    "model": "Model 3",
    "year": 2018,
    "price": 957801,
    "originalPrice": 1023156,
    "fuel": "Petrol",
    "mileage": "13.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "ABS",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "81",
    "make": "BMW",
    "model": "Elantra",
    "year": 2016,
    "price": 1056740,
    "originalPrice": 1143557,
    "fuel": "Hybrid",
    "mileage": "17.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Airbags",
      "Leather Seats",
      "Navigation",
      "Bluetooth",
      "Sunroof",
      "AC"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "82",
    "make": "Honda",
    "model": "Model 3",
    "year": 2019,
    "price": 1321986,
    "originalPrice": 1436957,
    "fuel": "Petrol",
    "mileage": "17.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "83",
    "make": "Chevrolet",
    "model": "Malibu",
    "year": 2012,
    "price": 654732,
    "originalPrice": 730639,
    "fuel": "Hybrid",
    "mileage": "17.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "AC",
      "Airbags",
      "Power Steering",
      "Leather Seats",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "84",
    "make": "Chevrolet",
    "model": "C-Class",
    "year": 2017,
    "price": 838068,
    "originalPrice": 978327,
    "fuel": "Electric",
    "mileage": "12.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "AC",
      "Sunroof",
      "Leather Seats",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "85",
    "make": "Tesla",
    "model": "Civic",
    "year": 2019,
    "price": 1267751,
    "originalPrice": 1373041,
    "fuel": "Diesel",
    "mileage": "14.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Leather Seats",
      "Airbags",
      "Bluetooth"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "86",
    "make": "Kia",
    "model": "Mustang",
    "year": 2013,
    "price": 892246,
    "originalPrice": 957449,
    "fuel": "Electric",
    "mileage": "18.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "87",
    "make": "Mercedes",
    "model": "Mustang",
    "year": 2014,
    "price": 1422372,
    "originalPrice": 1523598,
    "fuel": "Hybrid",
    "mileage": "23.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "ABS",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "88",
    "make": "Kia",
    "model": "Sportage",
    "year": 2016,
    "price": 1357880,
    "originalPrice": 1393560,
    "fuel": "Diesel",
    "mileage": "18.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "89",
    "make": "BMW",
    "model": "C-Class",
    "year": 2018,
    "price": 791747,
    "originalPrice": 862476,
    "fuel": "Petrol",
    "mileage": "19.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Navigation",
      "ABS",
      "Bluetooth",
      "Leather Seats",
      "AC",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "90",
    "make": "Chevrolet",
    "model": "X5",
    "year": 2022,
    "price": 1213524,
    "originalPrice": 1214033,
    "fuel": "Hybrid",
    "mileage": "11.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "Airbags",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "91",
    "make": "Kia",
    "model": "C-Class",
    "year": 2021,
    "price": 789008,
    "originalPrice": 948128,
    "fuel": "Electric",
    "mileage": "23.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "AC",
      "Power Steering",
      "Bluetooth"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "92",
    "make": "Chevrolet",
    "model": "Elantra",
    "year": 2020,
    "price": 1091453,
    "originalPrice": 1183950,
    "fuel": "Hybrid",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Bluetooth",
      "AC",
      "Power Steering",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "93",
    "make": "Kia",
    "model": "Elantra",
    "year": 2010,
    "price": 1215927,
    "originalPrice": 1310925,
    "fuel": "Electric",
    "mileage": "19.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Power Steering",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "94",
    "make": "Mercedes",
    "model": "C-Class",
    "year": 2018,
    "price": 1437891,
    "originalPrice": 1602913,
    "fuel": "Electric",
    "mileage": "14.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Bluetooth",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "95",
    "make": "Chevrolet",
    "model": "Malibu",
    "year": 2017,
    "price": 1102076,
    "originalPrice": 1154856,
    "fuel": "Hybrid",
    "mileage": "11.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Power Steering",
      "AC",
      "ABS",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "96",
    "make": "Tesla",
    "model": "Q7",
    "year": 2012,
    "price": 989610,
    "originalPrice": 1050856,
    "fuel": "Petrol",
    "mileage": "14.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "Navigation",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "97",
    "make": "Honda",
    "model": "C-Class",
    "year": 2024,
    "price": 741163,
    "originalPrice": 919410,
    "fuel": "Diesel",
    "mileage": "22.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "Power Steering",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "98",
    "make": "Mercedes",
    "model": "Malibu",
    "year": 2020,
    "price": 649319,
    "originalPrice": 843177,
    "fuel": "Petrol",
    "mileage": "11.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Bluetooth",
      "Airbags",
      "AC",
      "ABS",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "99",
    "make": "BMW",
    "model": "Malibu",
    "year": 2013,
    "price": 761256,
    "originalPrice": 896590,
    "fuel": "Electric",
    "mileage": "19.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Airbags",
      "Bluetooth",
      "Sunroof",
      "AC",
      "ABS",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "100",
    "make": "Kia",
    "model": "Mustang",
    "year": 2023,
    "price": 1153838,
    "originalPrice": 1167817,
    "fuel": "Diesel",
    "mileage": "22.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "AC"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  }
];