export const DUMMY_CARS = [
  {
    "id": "1",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2012,
    "price": 1371778,
    "originalPrice": 1474155,
    "fuel": "Diesel",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Navigation",
      "AC",
      "ABS",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "2",
    "make": "Kia",
    "model": "Model 3",
    "year": 2023,
    "price": 1471328,
    "originalPrice": 1588263,
    "fuel": "Electric",
    "mileage": "16.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Airbags",
      "Navigation",
      "Leather Seats",
      "AC",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "3",
    "make": "Hyundai",
    "model": "Malibu",
    "year": 2012,
    "price": 1404111,
    "originalPrice": 1494729,
    "fuel": "Petrol",
    "mileage": "24.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Power Steering",
      "AC",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "4",
    "make": "Hyundai",
    "model": "C-Class",
    "year": 2012,
    "price": 1025308,
    "originalPrice": 1143619,
    "fuel": "Petrol",
    "mileage": "13.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "Navigation",
      "ABS",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "5",
    "make": "Tesla",
    "model": "Civic",
    "year": 2016,
    "price": 641595,
    "originalPrice": 801474,
    "fuel": "Diesel",
    "mileage": "12.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "Navigation",
      "Airbags",
      "Sunroof",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "6",
    "make": "Ford",
    "model": "Mustang",
    "year": 2021,
    "price": 994615,
    "originalPrice": 1130875,
    "fuel": "Hybrid",
    "mileage": "14.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "7",
    "make": "Audi",
    "model": "Civic",
    "year": 2021,
    "price": 1055271,
    "originalPrice": 1175459,
    "fuel": "Diesel",
    "mileage": "10.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Airbags",
      "ABS",
      "Navigation",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "8",
    "make": "Kia",
    "model": "C-Class",
    "year": 2021,
    "price": 1163474,
    "originalPrice": 1315322,
    "fuel": "Diesel",
    "mileage": "15.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "AC",
      "Airbags",
      "Bluetooth",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "9",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2017,
    "price": 1306428,
    "originalPrice": 1371090,
    "fuel": "Petrol",
    "mileage": "25.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "AC",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "10",
    "make": "Hyundai",
    "model": "Elantra",
    "year": 2010,
    "price": 1409037,
    "originalPrice": 1546124,
    "fuel": "Petrol",
    "mileage": "24.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "ABS",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "11",
    "make": "Ford",
    "model": "Malibu",
    "year": 2016,
    "price": 1027996,
    "originalPrice": 1171868,
    "fuel": "Hybrid",
    "mileage": "23.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "ABS",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "12",
    "make": "Tesla",
    "model": "Sportage",
    "year": 2010,
    "price": 782029,
    "originalPrice": 943020,
    "fuel": "Petrol",
    "mileage": "17.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Power Steering",
      "Airbags",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "13",
    "make": "Audi",
    "model": "X5",
    "year": 2018,
    "price": 655143,
    "originalPrice": 735032,
    "fuel": "Hybrid",
    "mileage": "24.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Power Steering",
      "ABS",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "14",
    "make": "Toyota",
    "model": "Elantra",
    "year": 2023,
    "price": 1076737,
    "originalPrice": 1247098,
    "fuel": "Electric",
    "mileage": "12.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Navigation",
      "Power Steering",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "15",
    "make": "Ford",
    "model": "Sportage",
    "year": 2015,
    "price": 1166076,
    "originalPrice": 1320415,
    "fuel": "Diesel",
    "mileage": "15.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "AC",
      "Leather Seats",
      "Sunroof",
      "Airbags",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "16",
    "make": "Hyundai",
    "model": "Q7",
    "year": 2014,
    "price": 1299466,
    "originalPrice": 1486439,
    "fuel": "Petrol",
    "mileage": "13.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Bluetooth",
      "Leather Seats",
      "AC",
      "ABS",
      "Airbags",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "17",
    "make": "BMW",
    "model": "Mustang",
    "year": 2011,
    "price": 1414178,
    "originalPrice": 1445779,
    "fuel": "Diesel",
    "mileage": "17.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Power Steering",
      "Bluetooth",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "18",
    "make": "Kia",
    "model": "Elantra",
    "year": 2012,
    "price": 795354,
    "originalPrice": 880003,
    "fuel": "Petrol",
    "mileage": "15.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Power Steering",
      "AC",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "19",
    "make": "Toyota",
    "model": "Q7",
    "year": 2012,
    "price": 974661,
    "originalPrice": 1105525,
    "fuel": "Diesel",
    "mileage": "19.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Airbags",
      "Leather Seats",
      "ABS",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "20",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2020,
    "price": 1302730,
    "originalPrice": 1338667,
    "fuel": "Hybrid",
    "mileage": "11.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Airbags",
      "Leather Seats",
      "AC",
      "ABS",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "21",
    "make": "Audi",
    "model": "Elantra",
    "year": 2024,
    "price": 784345,
    "originalPrice": 981402,
    "fuel": "Diesel",
    "mileage": "10.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "22",
    "make": "Hyundai",
    "model": "X5",
    "year": 2010,
    "price": 782628,
    "originalPrice": 799789,
    "fuel": "Diesel",
    "mileage": "16.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "23",
    "make": "Hyundai",
    "model": "Model 3",
    "year": 2015,
    "price": 1470393,
    "originalPrice": 1479632,
    "fuel": "Electric",
    "mileage": "13.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "24",
    "make": "Ford",
    "model": "Malibu",
    "year": 2017,
    "price": 944792,
    "originalPrice": 977661,
    "fuel": "Electric",
    "mileage": "18.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "Sunroof",
      "Bluetooth",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "25",
    "make": "Audi",
    "model": "Malibu",
    "year": 2011,
    "price": 982270,
    "originalPrice": 1092300,
    "fuel": "Electric",
    "mileage": "14.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "Navigation",
      "Airbags",
      "ABS",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "26",
    "make": "BMW",
    "model": "X5",
    "year": 2019,
    "price": 1229247,
    "originalPrice": 1347961,
    "fuel": "Petrol",
    "mileage": "21.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Leather Seats",
      "Sunroof",
      "ABS",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "27",
    "make": "Audi",
    "model": "Elantra",
    "year": 2013,
    "price": 1313792,
    "originalPrice": 1338710,
    "fuel": "Electric",
    "mileage": "16.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "ABS",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "28",
    "make": "Hyundai",
    "model": "Civic",
    "year": 2022,
    "price": 835389,
    "originalPrice": 1004837,
    "fuel": "Electric",
    "mileage": "20.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "29",
    "make": "Kia",
    "model": "Q7",
    "year": 2022,
    "price": 1043810,
    "originalPrice": 1052822,
    "fuel": "Petrol",
    "mileage": "19.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "30",
    "make": "Mercedes",
    "model": "C-Class",
    "year": 2012,
    "price": 1497167,
    "originalPrice": 1610333,
    "fuel": "Diesel",
    "mileage": "22.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "31",
    "make": "Ford",
    "model": "Malibu",
    "year": 2015,
    "price": 1219480,
    "originalPrice": 1345543,
    "fuel": "Petrol",
    "mileage": "20.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "AC",
      "ABS",
      "Navigation",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "32",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2017,
    "price": 1037182,
    "originalPrice": 1234900,
    "fuel": "Petrol",
    "mileage": "10.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Navigation",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "33",
    "make": "Tesla",
    "model": "Civic",
    "year": 2024,
    "price": 1361390,
    "originalPrice": 1517271,
    "fuel": "Electric",
    "mileage": "12.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "AC",
      "Airbags",
      "ABS",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "34",
    "make": "Ford",
    "model": "Corolla",
    "year": 2021,
    "price": 587903,
    "originalPrice": 613387,
    "fuel": "Petrol",
    "mileage": "19.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Bluetooth",
      "Power Steering",
      "Airbags",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "35",
    "make": "Audi",
    "model": "Malibu",
    "year": 2015,
    "price": 1346437,
    "originalPrice": 1441112,
    "fuel": "Hybrid",
    "mileage": "21.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "ABS",
      "AC",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "36",
    "make": "BMW",
    "model": "Q7",
    "year": 2010,
    "price": 532978,
    "originalPrice": 643859,
    "fuel": "Petrol",
    "mileage": "21.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Sunroof",
      "Airbags",
      "Leather Seats",
      "Bluetooth",
      "ABS",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "37",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2016,
    "price": 863665,
    "originalPrice": 1055057,
    "fuel": "Electric",
    "mileage": "24.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Sunroof",
      "Power Steering",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "38",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2014,
    "price": 636626,
    "originalPrice": 767938,
    "fuel": "Hybrid",
    "mileage": "17.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Airbags",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "39",
    "make": "Tesla",
    "model": "Q7",
    "year": 2010,
    "price": 1193348,
    "originalPrice": 1241722,
    "fuel": "Diesel",
    "mileage": "17.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "AC",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "40",
    "make": "Honda",
    "model": "Sportage",
    "year": 2022,
    "price": 1405018,
    "originalPrice": 1452199,
    "fuel": "Electric",
    "mileage": "12.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "AC",
      "Navigation",
      "Bluetooth",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "41",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2019,
    "price": 1377415,
    "originalPrice": 1421323,
    "fuel": "Diesel",
    "mileage": "22.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Power Steering",
      "Navigation",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "42",
    "make": "Ford",
    "model": "Sportage",
    "year": 2018,
    "price": 1451705,
    "originalPrice": 1589518,
    "fuel": "Petrol",
    "mileage": "22.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "AC",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "43",
    "make": "Honda",
    "model": "Corolla",
    "year": 2015,
    "price": 1376665,
    "originalPrice": 1387668,
    "fuel": "Diesel",
    "mileage": "23.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Power Steering",
      "Sunroof",
      "AC",
      "Leather Seats",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "44",
    "make": "Honda",
    "model": "Civic",
    "year": 2014,
    "price": 1102611,
    "originalPrice": 1118096,
    "fuel": "Hybrid",
    "mileage": "24.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "AC",
      "ABS",
      "Leather Seats",
      "Navigation",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "45",
    "make": "Hyundai",
    "model": "Elantra",
    "year": 2016,
    "price": 1069414,
    "originalPrice": 1194511,
    "fuel": "Electric",
    "mileage": "20.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "Power Steering",
      "ABS",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "46",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2020,
    "price": 1351028,
    "originalPrice": 1542919,
    "fuel": "Petrol",
    "mileage": "19.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "ABS",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "47",
    "make": "Audi",
    "model": "Malibu",
    "year": 2023,
    "price": 1469034,
    "originalPrice": 1538223,
    "fuel": "Hybrid",
    "mileage": "17.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Navigation",
      "AC",
      "Airbags",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "48",
    "make": "Tesla",
    "model": "Model 3",
    "year": 2019,
    "price": 960600,
    "originalPrice": 978712,
    "fuel": "Hybrid",
    "mileage": "11.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Leather Seats",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "49",
    "make": "BMW",
    "model": "Elantra",
    "year": 2023,
    "price": 775695,
    "originalPrice": 830104,
    "fuel": "Petrol",
    "mileage": "15.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "AC",
      "ABS",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "50",
    "make": "Audi",
    "model": "C-Class",
    "year": 2018,
    "price": 1097550,
    "originalPrice": 1189333,
    "fuel": "Electric",
    "mileage": "23.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "51",
    "make": "Hyundai",
    "model": "X5",
    "year": 2019,
    "price": 1103354,
    "originalPrice": 1197535,
    "fuel": "Electric",
    "mileage": "23.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "ABS",
      "Navigation",
      "AC",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "52",
    "make": "Tesla",
    "model": "X5",
    "year": 2016,
    "price": 992630,
    "originalPrice": 1168770,
    "fuel": "Electric",
    "mileage": "16.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Leather Seats",
      "Bluetooth",
      "Airbags",
      "Sunroof",
      "ABS",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "53",
    "make": "Honda",
    "model": "X5",
    "year": 2014,
    "price": 1249371,
    "originalPrice": 1303333,
    "fuel": "Hybrid",
    "mileage": "13.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Power Steering",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "54",
    "make": "Honda",
    "model": "Civic",
    "year": 2013,
    "price": 1106969,
    "originalPrice": 1109295,
    "fuel": "Petrol",
    "mileage": "14.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Leather Seats",
      "ABS",
      "Airbags",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "55",
    "make": "Honda",
    "model": "Corolla",
    "year": 2011,
    "price": 961140,
    "originalPrice": 1035679,
    "fuel": "Hybrid",
    "mileage": "16.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "ABS",
      "AC",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "56",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2013,
    "price": 1217471,
    "originalPrice": 1397425,
    "fuel": "Electric",
    "mileage": "18.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "Bluetooth",
      "ABS",
      "Power Steering",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "57",
    "make": "Honda",
    "model": "Elantra",
    "year": 2015,
    "price": 858622,
    "originalPrice": 965241,
    "fuel": "Hybrid",
    "mileage": "22.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Navigation",
      "Leather Seats",
      "Sunroof",
      "AC",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "58",
    "make": "Audi",
    "model": "Corolla",
    "year": 2019,
    "price": 675238,
    "originalPrice": 850210,
    "fuel": "Diesel",
    "mileage": "19.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Bluetooth",
      "Airbags",
      "AC"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "59",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2016,
    "price": 893455,
    "originalPrice": 1010817,
    "fuel": "Hybrid",
    "mileage": "23.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Airbags",
      "AC",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "60",
    "make": "Ford",
    "model": "Corolla",
    "year": 2016,
    "price": 538212,
    "originalPrice": 631784,
    "fuel": "Hybrid",
    "mileage": "17.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Leather Seats",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "Navigation",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "61",
    "make": "BMW",
    "model": "Corolla",
    "year": 2010,
    "price": 630643,
    "originalPrice": 703828,
    "fuel": "Petrol",
    "mileage": "17.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "62",
    "make": "Honda",
    "model": "X5",
    "year": 2018,
    "price": 600786,
    "originalPrice": 705708,
    "fuel": "Petrol",
    "mileage": "14.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "AC",
      "Power Steering",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "63",
    "make": "Ford",
    "model": "Mustang",
    "year": 2011,
    "price": 602284,
    "originalPrice": 680588,
    "fuel": "Petrol",
    "mileage": "15.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Airbags",
      "Leather Seats",
      "Power Steering",
      "ABS",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "64",
    "make": "Kia",
    "model": "Elantra",
    "year": 2021,
    "price": 771274,
    "originalPrice": 935696,
    "fuel": "Electric",
    "mileage": "11.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Airbags",
      "AC",
      "Navigation",
      "ABS",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "65",
    "make": "Tesla",
    "model": "X5",
    "year": 2011,
    "price": 819957,
    "originalPrice": 989295,
    "fuel": "Diesel",
    "mileage": "19.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "Sunroof",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "66",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2021,
    "price": 690512,
    "originalPrice": 719766,
    "fuel": "Diesel",
    "mileage": "18.5 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Airbags",
      "AC",
      "Navigation",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "67",
    "make": "Toyota",
    "model": "Q7",
    "year": 2024,
    "price": 1430155,
    "originalPrice": 1457572,
    "fuel": "Electric",
    "mileage": "22.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "ABS",
      "Airbags",
      "Sunroof",
      "Leather Seats",
      "Navigation",
      "Power Steering",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "68",
    "make": "Ford",
    "model": "X5",
    "year": 2018,
    "price": 1064350,
    "originalPrice": 1207058,
    "fuel": "Petrol",
    "mileage": "10.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "Bluetooth",
      "Power Steering",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "69",
    "make": "Audi",
    "model": "Q7",
    "year": 2021,
    "price": 1230982,
    "originalPrice": 1279399,
    "fuel": "Petrol",
    "mileage": "10.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "AC",
      "Sunroof",
      "Navigation",
      "Airbags",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "70",
    "make": "Audi",
    "model": "Model 3",
    "year": 2015,
    "price": 1032780,
    "originalPrice": 1152698,
    "fuel": "Petrol",
    "mileage": "14.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "71",
    "make": "Honda",
    "model": "C-Class",
    "year": 2011,
    "price": 625112,
    "originalPrice": 711504,
    "fuel": "Hybrid",
    "mileage": "16.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Navigation",
      "ABS",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "72",
    "make": "Toyota",
    "model": "Q7",
    "year": 2023,
    "price": 695934,
    "originalPrice": 809212,
    "fuel": "Diesel",
    "mileage": "10.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Power Steering",
      "Navigation",
      "ABS",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "73",
    "make": "Kia",
    "model": "Sportage",
    "year": 2012,
    "price": 844491,
    "originalPrice": 866371,
    "fuel": "Hybrid",
    "mileage": "21.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Navigation",
      "AC",
      "Power Steering",
      "Bluetooth",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "74",
    "make": "Chevrolet",
    "model": "Sportage",
    "year": 2016,
    "price": 800850,
    "originalPrice": 900353,
    "fuel": "Electric",
    "mileage": "13.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "Navigation",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "75",
    "make": "Mercedes",
    "model": "Mustang",
    "year": 2012,
    "price": 1390682,
    "originalPrice": 1518760,
    "fuel": "Electric",
    "mileage": "18.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Airbags",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "76",
    "make": "BMW",
    "model": "Malibu",
    "year": 2024,
    "price": 1234339,
    "originalPrice": 1308971,
    "fuel": "Electric",
    "mileage": "22.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Power Steering",
      "Navigation"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "77",
    "make": "BMW",
    "model": "Corolla",
    "year": 2019,
    "price": 546042,
    "originalPrice": 574382,
    "fuel": "Hybrid",
    "mileage": "16.0 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Leather Seats",
      "ABS",
      "Navigation",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "78",
    "make": "Tesla",
    "model": "Q7",
    "year": 2015,
    "price": 1398843,
    "originalPrice": 1503657,
    "fuel": "Diesel",
    "mileage": "14.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "79",
    "make": "Chevrolet",
    "model": "Corolla",
    "year": 2012,
    "price": 754114,
    "originalPrice": 942196,
    "fuel": "Hybrid",
    "mileage": "22.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Airbags",
      "Leather Seats",
      "Power Steering",
      "Navigation",
      "Bluetooth",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "80",
    "make": "Audi",
    "model": "Mustang",
    "year": 2019,
    "price": 1068635,
    "originalPrice": 1111436,
    "fuel": "Petrol",
    "mileage": "15.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Sunroof",
      "Bluetooth",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "81",
    "make": "Honda",
    "model": "Q7",
    "year": 2013,
    "price": 1012478,
    "originalPrice": 1119412,
    "fuel": "Hybrid",
    "mileage": "12.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Airbags",
      "Leather Seats",
      "Sunroof",
      "AC"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "82",
    "make": "Toyota",
    "model": "Model 3",
    "year": 2016,
    "price": 1151250,
    "originalPrice": 1225264,
    "fuel": "Petrol",
    "mileage": "18.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Bluetooth",
      "AC",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "83",
    "make": "Kia",
    "model": "X5",
    "year": 2022,
    "price": 1101347,
    "originalPrice": 1165777,
    "fuel": "Diesel",
    "mileage": "22.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "AC",
      "Airbags",
      "Sunroof",
      "ABS",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "84",
    "make": "BMW",
    "model": "X5",
    "year": 2022,
    "price": 736534,
    "originalPrice": 851846,
    "fuel": "Diesel",
    "mileage": "15.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "ABS",
      "AC",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "85",
    "make": "Kia",
    "model": "Corolla",
    "year": 2010,
    "price": 527300,
    "originalPrice": 529560,
    "fuel": "Petrol",
    "mileage": "20.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Airbags",
      "Leather Seats",
      "AC",
      "Bluetooth",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "86",
    "make": "Honda",
    "model": "Elantra",
    "year": 2012,
    "price": 1420903,
    "originalPrice": 1466349,
    "fuel": "Hybrid",
    "mileage": "12.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "ABS",
      "Sunroof",
      "Airbags",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "87",
    "make": "Honda",
    "model": "Sportage",
    "year": 2015,
    "price": 589113,
    "originalPrice": 721157,
    "fuel": "Hybrid",
    "mileage": "14.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Airbags",
      "AC",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "88",
    "make": "Honda",
    "model": "Corolla",
    "year": 2019,
    "price": 1400784,
    "originalPrice": 1498890,
    "fuel": "Hybrid",
    "mileage": "21.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "ABS",
      "Leather Seats",
      "Sunroof",
      "AC",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "89",
    "make": "Ford",
    "model": "X5",
    "year": 2015,
    "price": 857428,
    "originalPrice": 1018470,
    "fuel": "Hybrid",
    "mileage": "17.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "90",
    "make": "Chevrolet",
    "model": "Model 3",
    "year": 2011,
    "price": 1326939,
    "originalPrice": 1355287,
    "fuel": "Electric",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Navigation",
      "AC"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "91",
    "make": "Hyundai",
    "model": "C-Class",
    "year": 2014,
    "price": 667524,
    "originalPrice": 689288,
    "fuel": "Diesel",
    "mileage": "16.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "ABS",
      "Bluetooth",
      "Navigation",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "92",
    "make": "Chevrolet",
    "model": "X5",
    "year": 2019,
    "price": 1301319,
    "originalPrice": 1465167,
    "fuel": "Hybrid",
    "mileage": "18.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "Bluetooth",
      "ABS",
      "Leather Seats",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "93",
    "make": "Honda",
    "model": "Elantra",
    "year": 2021,
    "price": 746109,
    "originalPrice": 875296,
    "fuel": "Hybrid",
    "mileage": "18.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "Airbags",
      "Leather Seats",
      "Bluetooth",
      "Navigation",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "94",
    "make": "Audi",
    "model": "Malibu",
    "year": 2013,
    "price": 929801,
    "originalPrice": 994801,
    "fuel": "Diesel",
    "mileage": "10.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Power Steering",
      "Bluetooth",
      "ABS",
      "AC"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "95",
    "make": "Hyundai",
    "model": "Elantra",
    "year": 2011,
    "price": 1014019,
    "originalPrice": 1104564,
    "fuel": "Electric",
    "mileage": "22.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "96",
    "make": "BMW",
    "model": "Civic",
    "year": 2018,
    "price": 1442147,
    "originalPrice": 1638807,
    "fuel": "Electric",
    "mileage": "23.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Bluetooth",
      "Navigation",
      "ABS",
      "Power Steering",
      "Leather Seats",
      "AC"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "97",
    "make": "Toyota",
    "model": "Corolla",
    "year": 2024,
    "price": 1100172,
    "originalPrice": 1170819,
    "fuel": "Petrol",
    "mileage": "21.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Sunroof",
      "Bluetooth",
      "Leather Seats",
      "AC",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "98",
    "make": "Hyundai",
    "model": "Mustang",
    "year": 2021,
    "price": 636139,
    "originalPrice": 782215,
    "fuel": "Electric",
    "mileage": "19.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "Leather Seats",
      "Bluetooth",
      "Sunroof",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "99",
    "make": "Audi",
    "model": "X5",
    "year": 2012,
    "price": 1308963,
    "originalPrice": 1381400,
    "fuel": "Electric",
    "mileage": "15.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "AC"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "100",
    "make": "Hyundai",
    "model": "Civic",
    "year": 2019,
    "price": 1224052,
    "originalPrice": 1345093,
    "fuel": "Electric",
    "mileage": "24.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Bluetooth",
      "Airbags",
      "Power Steering",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "SUV"
  }
];