export const DUMMY_CARS = [
  {
    "id": "1",
    "make": "Honda",
    "model": "Q7",
    "year": 2014,
    "price": 750883,
    "originalPrice": 930605,
    "fuel": "Hybrid",
    "mileage": "20.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Power Steering",
      "ABS"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "2",
    "make": "Mercedes",
    "model": "Mustang",
    "year": 2015,
    "price": 671890,
    "originalPrice": 821789,
    "fuel": "Hybrid",
    "mileage": "14.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "3",
    "make": "Mercedes",
    "model": "Q7",
    "year": 2015,
    "price": 1013846,
    "originalPrice": 1110873,
    "fuel": "Petrol",
    "mileage": "13.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "Navigation",
      "Power Steering",
      "AC"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "4",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2013,
    "price": 784205,
    "originalPrice": 839787,
    "fuel": "Diesel",
    "mileage": "23.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Navigation",
      "Leather Seats",
      "AC",
      "ABS",
      "Sunroof"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "5",
    "make": "Kia",
    "model": "Malibu",
    "year": 2022,
    "price": 511389,
    "originalPrice": 643595,
    "fuel": "Hybrid",
    "mileage": "18.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Leather Seats"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "6",
    "make": "Tesla",
    "model": "Mustang",
    "year": 2021,
    "price": 1115136,
    "originalPrice": 1243757,
    "fuel": "Electric",
    "mileage": "19.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "ABS",
      "Power Steering",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "7",
    "make": "Mercedes",
    "model": "Model 3",
    "year": 2011,
    "price": 608979,
    "originalPrice": 632081,
    "fuel": "Hybrid",
    "mileage": "19.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "ABS",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "8",
    "make": "BMW",
    "model": "Malibu",
    "year": 2014,
    "price": 576343,
    "originalPrice": 773937,
    "fuel": "Petrol",
    "mileage": "10.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "Bluetooth",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "9",
    "make": "Tesla",
    "model": "Sportage",
    "year": 2011,
    "price": 1224059,
    "originalPrice": 1312347,
    "fuel": "Hybrid",
    "mileage": "18.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Bluetooth",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "10",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2010,
    "price": 1116864,
    "originalPrice": 1124171,
    "fuel": "Petrol",
    "mileage": "16.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "AC",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "11",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2019,
    "price": 1375834,
    "originalPrice": 1424333,
    "fuel": "Petrol",
    "mileage": "19.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "12",
    "make": "Audi",
    "model": "Malibu",
    "year": 2017,
    "price": 1448099,
    "originalPrice": 1632924,
    "fuel": "Electric",
    "mileage": "18.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Airbags",
      "ABS",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "13",
    "make": "Honda",
    "model": "Model 3",
    "year": 2021,
    "price": 1161748,
    "originalPrice": 1165532,
    "fuel": "Diesel",
    "mileage": "23.8 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "Airbags",
      "ABS",
      "Bluetooth",
      "AC"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "14",
    "make": "Kia",
    "model": "X5",
    "year": 2012,
    "price": 1055630,
    "originalPrice": 1177813,
    "fuel": "Electric",
    "mileage": "22.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "AC",
      "Airbags",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "15",
    "make": "Audi",
    "model": "C-Class",
    "year": 2015,
    "price": 664552,
    "originalPrice": 758116,
    "fuel": "Petrol",
    "mileage": "18.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Power Steering",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "16",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2024,
    "price": 943098,
    "originalPrice": 1000324,
    "fuel": "Hybrid",
    "mileage": "21.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "AC",
      "Airbags",
      "Power Steering",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "17",
    "make": "Honda",
    "model": "Corolla",
    "year": 2017,
    "price": 1005940,
    "originalPrice": 1193265,
    "fuel": "Petrol",
    "mileage": "11.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Power Steering",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "18",
    "make": "Honda",
    "model": "Model 3",
    "year": 2016,
    "price": 806863,
    "originalPrice": 867461,
    "fuel": "Electric",
    "mileage": "20.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Airbags",
      "Bluetooth",
      "Sunroof",
      "AC",
      "Navigation"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "19",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2014,
    "price": 1178841,
    "originalPrice": 1184708,
    "fuel": "Electric",
    "mileage": "21.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "Airbags",
      "Bluetooth",
      "ABS",
      "Power Steering",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "20",
    "make": "Honda",
    "model": "Model 3",
    "year": 2023,
    "price": 1021532,
    "originalPrice": 1038058,
    "fuel": "Diesel",
    "mileage": "16.1 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Leather Seats",
      "Sunroof",
      "AC"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "21",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2017,
    "price": 597527,
    "originalPrice": 779704,
    "fuel": "Petrol",
    "mileage": "12.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Bluetooth",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "22",
    "make": "Hyundai",
    "model": "Q7",
    "year": 2015,
    "price": 1277377,
    "originalPrice": 1310711,
    "fuel": "Electric",
    "mileage": "22.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "Power Steering",
      "Bluetooth",
      "ABS",
      "Navigation",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "23",
    "make": "Mercedes",
    "model": "X5",
    "year": 2016,
    "price": 1063192,
    "originalPrice": 1092943,
    "fuel": "Electric",
    "mileage": "13.0 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Bluetooth",
      "Leather Seats",
      "Navigation",
      "Power Steering",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "24",
    "make": "Audi",
    "model": "Elantra",
    "year": 2024,
    "price": 926177,
    "originalPrice": 1004708,
    "fuel": "Hybrid",
    "mileage": "21.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Sunroof",
      "Leather Seats",
      "AC"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "25",
    "make": "Mercedes",
    "model": "Corolla",
    "year": 2023,
    "price": 673450,
    "originalPrice": 689834,
    "fuel": "Diesel",
    "mileage": "18.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Airbags",
      "Sunroof",
      "Leather Seats",
      "AC",
      "ABS"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "26",
    "make": "BMW",
    "model": "X5",
    "year": 2020,
    "price": 939213,
    "originalPrice": 1017615,
    "fuel": "Diesel",
    "mileage": "21.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "27",
    "make": "Toyota",
    "model": "X5",
    "year": 2024,
    "price": 935911,
    "originalPrice": 1035414,
    "fuel": "Hybrid",
    "mileage": "11.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Sunroof",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "28",
    "make": "Ford",
    "model": "X5",
    "year": 2022,
    "price": 1385422,
    "originalPrice": 1554402,
    "fuel": "Petrol",
    "mileage": "23.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Sunroof",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "29",
    "make": "Hyundai",
    "model": "C-Class",
    "year": 2021,
    "price": 750872,
    "originalPrice": 777626,
    "fuel": "Petrol",
    "mileage": "18.1 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "Power Steering",
      "Sunroof",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "30",
    "make": "Tesla",
    "model": "Civic",
    "year": 2017,
    "price": 667824,
    "originalPrice": 673273,
    "fuel": "Electric",
    "mileage": "23.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "ABS",
      "Bluetooth",
      "Power Steering",
      "Navigation",
      "AC"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "31",
    "make": "Mercedes",
    "model": "Model 3",
    "year": 2014,
    "price": 1479475,
    "originalPrice": 1535650,
    "fuel": "Petrol",
    "mileage": "24.6 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Sunroof",
      "ABS",
      "Navigation",
      "Power Steering",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "32",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2017,
    "price": 1480173,
    "originalPrice": 1578785,
    "fuel": "Petrol",
    "mileage": "24.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "ABS",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "33",
    "make": "Ford",
    "model": "Corolla",
    "year": 2018,
    "price": 681974,
    "originalPrice": 763048,
    "fuel": "Electric",
    "mileage": "24.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "AC",
      "Airbags",
      "Sunroof",
      "Bluetooth",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "34",
    "make": "Mercedes",
    "model": "Q7",
    "year": 2024,
    "price": 1165950,
    "originalPrice": 1179453,
    "fuel": "Diesel",
    "mileage": "23.5 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "Navigation",
      "Airbags",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "35",
    "make": "Honda",
    "model": "Mustang",
    "year": 2021,
    "price": 1168650,
    "originalPrice": 1360541,
    "fuel": "Petrol",
    "mileage": "20.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Navigation",
      "ABS",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "36",
    "make": "Ford",
    "model": "Model 3",
    "year": 2018,
    "price": 1388383,
    "originalPrice": 1485081,
    "fuel": "Hybrid",
    "mileage": "23.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Navigation",
      "Bluetooth",
      "Leather Seats",
      "Airbags",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "37",
    "make": "Chevrolet",
    "model": "Civic",
    "year": 2014,
    "price": 1356124,
    "originalPrice": 1530809,
    "fuel": "Hybrid",
    "mileage": "15.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "Navigation",
      "Power Steering",
      "Airbags",
      "Sunroof",
      "Bluetooth",
      "AC"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "38",
    "make": "Kia",
    "model": "Malibu",
    "year": 2021,
    "price": 843405,
    "originalPrice": 922728,
    "fuel": "Hybrid",
    "mileage": "20.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Leather Seats",
      "Airbags",
      "Sunroof",
      "ABS",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "39",
    "make": "Mercedes",
    "model": "C-Class",
    "year": 2010,
    "price": 939846,
    "originalPrice": 1055482,
    "fuel": "Hybrid",
    "mileage": "20.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "AC",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "40",
    "make": "Chevrolet",
    "model": "Model 3",
    "year": 2014,
    "price": 1202701,
    "originalPrice": 1347630,
    "fuel": "Diesel",
    "mileage": "19.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Navigation",
      "ABS",
      "Bluetooth",
      "AC",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "41",
    "make": "Ford",
    "model": "Civic",
    "year": 2023,
    "price": 1462906,
    "originalPrice": 1619726,
    "fuel": "Electric",
    "mileage": "13.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Sunroof",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "42",
    "make": "Audi",
    "model": "Model 3",
    "year": 2010,
    "price": 1289208,
    "originalPrice": 1376560,
    "fuel": "Diesel",
    "mileage": "16.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Leather Seats",
      "Power Steering",
      "Airbags",
      "Navigation",
      "Sunroof",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "43",
    "make": "Audi",
    "model": "Mustang",
    "year": 2023,
    "price": 942442,
    "originalPrice": 1113648,
    "fuel": "Hybrid",
    "mileage": "20.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "ABS",
      "Leather Seats",
      "Power Steering",
      "Airbags",
      "Navigation"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "44",
    "make": "Audi",
    "model": "Elantra",
    "year": 2016,
    "price": 846326,
    "originalPrice": 969303,
    "fuel": "Hybrid",
    "mileage": "10.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Navigation",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "45",
    "make": "Toyota",
    "model": "Mustang",
    "year": 2017,
    "price": 703580,
    "originalPrice": 867392,
    "fuel": "Hybrid",
    "mileage": "24.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Airbags",
      "Navigation",
      "AC",
      "Leather Seats",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "46",
    "make": "Toyota",
    "model": "X5",
    "year": 2010,
    "price": 1052207,
    "originalPrice": 1158619,
    "fuel": "Electric",
    "mileage": "23.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Airbags",
      "Sunroof",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "47",
    "make": "Kia",
    "model": "C-Class",
    "year": 2024,
    "price": 1494309,
    "originalPrice": 1606734,
    "fuel": "Electric",
    "mileage": "20.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "ABS",
      "Airbags",
      "AC",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "48",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2023,
    "price": 1252960,
    "originalPrice": 1425840,
    "fuel": "Hybrid",
    "mileage": "16.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Leather Seats",
      "Navigation",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "49",
    "make": "Audi",
    "model": "C-Class",
    "year": 2014,
    "price": 1409621,
    "originalPrice": 1423793,
    "fuel": "Electric",
    "mileage": "10.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "AC",
      "ABS"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "50",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2015,
    "price": 875484,
    "originalPrice": 1073912,
    "fuel": "Diesel",
    "mileage": "24.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "51",
    "make": "BMW",
    "model": "Corolla",
    "year": 2023,
    "price": 1111074,
    "originalPrice": 1242902,
    "fuel": "Electric",
    "mileage": "13.2 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "Airbags",
      "ABS",
      "AC",
      "Bluetooth",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "52",
    "make": "BMW",
    "model": "Elantra",
    "year": 2012,
    "price": 745520,
    "originalPrice": 804864,
    "fuel": "Hybrid",
    "mileage": "23.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Bluetooth",
      "AC",
      "Airbags",
      "ABS"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "SUV"
  },
  {
    "id": "53",
    "make": "Hyundai",
    "model": "Sportage",
    "year": 2015,
    "price": 694951,
    "originalPrice": 709840,
    "fuel": "Electric",
    "mileage": "13.2 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "Bluetooth",
      "ABS",
      "Power Steering",
      "AC",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "54",
    "make": "Honda",
    "model": "Civic",
    "year": 2014,
    "price": 904749,
    "originalPrice": 1102118,
    "fuel": "Hybrid",
    "mileage": "23.6 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Sunroof",
      "Airbags",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "55",
    "make": "Honda",
    "model": "X5",
    "year": 2020,
    "price": 1194125,
    "originalPrice": 1241055,
    "fuel": "Petrol",
    "mileage": "14.9 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Leather Seats",
      "Bluetooth",
      "Sunroof",
      "Power Steering",
      "Airbags"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "56",
    "make": "Honda",
    "model": "X5",
    "year": 2011,
    "price": 1108922,
    "originalPrice": 1254613,
    "fuel": "Hybrid",
    "mileage": "10.7 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "57",
    "make": "Chevrolet",
    "model": "Mustang",
    "year": 2018,
    "price": 672611,
    "originalPrice": 812727,
    "fuel": "Hybrid",
    "mileage": "12.9 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Airbags",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "58",
    "make": "Audi",
    "model": "Mustang",
    "year": 2018,
    "price": 763638,
    "originalPrice": 802966,
    "fuel": "Diesel",
    "mileage": "20.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Airbags",
      "Leather Seats",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "59",
    "make": "Ford",
    "model": "Sportage",
    "year": 2019,
    "price": 676865,
    "originalPrice": 856051,
    "fuel": "Hybrid",
    "mileage": "21.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "Navigation",
      "Bluetooth",
      "AC",
      "Leather Seats",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "60",
    "make": "BMW",
    "model": "Model 3",
    "year": 2012,
    "price": 1142861,
    "originalPrice": 1186480,
    "fuel": "Petrol",
    "mileage": "19.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "ABS",
      "Power Steering",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "61",
    "make": "Audi",
    "model": "Sportage",
    "year": 2024,
    "price": 837308,
    "originalPrice": 856602,
    "fuel": "Diesel",
    "mileage": "18.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Sunroof",
      "Bluetooth",
      "Navigation",
      "Airbags"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "62",
    "make": "Mercedes",
    "model": "Model 3",
    "year": 2023,
    "price": 1264322,
    "originalPrice": 1281413,
    "fuel": "Petrol",
    "mileage": "21.7 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "AC",
      "Navigation",
      "ABS",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "63",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2018,
    "price": 1298816,
    "originalPrice": 1381009,
    "fuel": "Petrol",
    "mileage": "20.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "AC",
      "Leather Seats",
      "ABS",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "64",
    "make": "Tesla",
    "model": "Q7",
    "year": 2010,
    "price": 1032798,
    "originalPrice": 1062787,
    "fuel": "Diesel",
    "mileage": "15.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Navigation",
      "Bluetooth",
      "AC",
      "ABS",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "65",
    "make": "Toyota",
    "model": "Mustang",
    "year": 2023,
    "price": 1143714,
    "originalPrice": 1223191,
    "fuel": "Diesel",
    "mileage": "19.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Bluetooth",
      "ABS",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "66",
    "make": "Ford",
    "model": "Civic",
    "year": 2016,
    "price": 1325265,
    "originalPrice": 1486562,
    "fuel": "Petrol",
    "mileage": "14.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Navigation",
      "Bluetooth"
    ],
    "seating": 2,
    "transmission": "Manual",
    "category": "Convertible"
  },
  {
    "id": "67",
    "make": "Audi",
    "model": "Corolla",
    "year": 2021,
    "price": 558210,
    "originalPrice": 706338,
    "fuel": "Hybrid",
    "mileage": "14.5 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Navigation",
      "ABS",
      "Sunroof",
      "Power Steering"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "68",
    "make": "Toyota",
    "model": "Model 3",
    "year": 2016,
    "price": 1188169,
    "originalPrice": 1306751,
    "fuel": "Hybrid",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "AC",
      "Power Steering",
      "Bluetooth",
      "Airbags",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "69",
    "make": "BMW",
    "model": "C-Class",
    "year": 2013,
    "price": 913510,
    "originalPrice": 1061752,
    "fuel": "Diesel",
    "mileage": "23.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "ABS",
      "Navigation",
      "AC",
      "Bluetooth"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "70",
    "make": "Tesla",
    "model": "Malibu",
    "year": 2019,
    "price": 629632,
    "originalPrice": 742399,
    "fuel": "Diesel",
    "mileage": "18.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 5,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "71",
    "make": "Hyundai",
    "model": "Model 3",
    "year": 2023,
    "price": 706685,
    "originalPrice": 800411,
    "fuel": "Electric",
    "mileage": "19.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "ABS",
      "AC",
      "Airbags",
      "Navigation",
      "Power Steering",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "72",
    "make": "Toyota",
    "model": "Elantra",
    "year": 2017,
    "price": 944379,
    "originalPrice": 965291,
    "fuel": "Petrol",
    "mileage": "20.9 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "Bluetooth",
      "Sunroof",
      "Power Steering",
      "Navigation",
      "Airbags",
      "AC"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "73",
    "make": "Chevrolet",
    "model": "Mustang",
    "year": 2012,
    "price": 1048013,
    "originalPrice": 1107959,
    "fuel": "Hybrid",
    "mileage": "23.3 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Bluetooth",
      "Airbags",
      "Power Steering"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "74",
    "make": "Mercedes",
    "model": "Malibu",
    "year": 2011,
    "price": 969971,
    "originalPrice": 1148970,
    "fuel": "Petrol",
    "mileage": "23.3 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Bluetooth"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "75",
    "make": "Chevrolet",
    "model": "Malibu",
    "year": 2011,
    "price": 737896,
    "originalPrice": 776576,
    "fuel": "Diesel",
    "mileage": "15.8 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "Power Steering",
      "Leather Seats",
      "Airbags",
      "ABS"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "76",
    "make": "Tesla",
    "model": "C-Class",
    "year": 2023,
    "price": 879358,
    "originalPrice": 1076955,
    "fuel": "Diesel",
    "mileage": "19.3 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "Navigation",
      "Power Steering"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "77",
    "make": "BMW",
    "model": "Q7",
    "year": 2019,
    "price": 853660,
    "originalPrice": 935037,
    "fuel": "Petrol",
    "mileage": "22.8 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Leather Seats",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "78",
    "make": "Toyota",
    "model": "Malibu",
    "year": 2024,
    "price": 795418,
    "originalPrice": 812736,
    "fuel": "Electric",
    "mileage": "18.0 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Airbags",
      "Leather Seats"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "79",
    "make": "Ford",
    "model": "Model 3",
    "year": 2011,
    "price": 1204756,
    "originalPrice": 1222422,
    "fuel": "Petrol",
    "mileage": "16.4 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Airbags",
      "Leather Seats",
      "ABS",
      "Sunroof",
      "Navigation",
      "Bluetooth"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "SUV"
  },
  {
    "id": "80",
    "make": "Kia",
    "model": "Q7",
    "year": 2014,
    "price": 743006,
    "originalPrice": 938107,
    "fuel": "Petrol",
    "mileage": "13.4 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Sunroof",
      "Bluetooth",
      "ABS",
      "Leather Seats",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "81",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2023,
    "price": 1106335,
    "originalPrice": 1159318,
    "fuel": "Hybrid",
    "mileage": "14.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Leather Seats",
      "ABS",
      "Bluetooth"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "82",
    "make": "Toyota",
    "model": "Corolla",
    "year": 2011,
    "price": 1083968,
    "originalPrice": 1193727,
    "fuel": "Petrol",
    "mileage": "22.4 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Bluetooth",
      "Leather Seats",
      "Sunroof",
      "Airbags"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Coupe"
  },
  {
    "id": "83",
    "make": "Chevrolet",
    "model": "Malibu",
    "year": 2010,
    "price": 1298588,
    "originalPrice": 1481460,
    "fuel": "Petrol",
    "mileage": "11.7 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Leather Seats",
      "AC",
      "Bluetooth",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "84",
    "make": "Tesla",
    "model": "Civic",
    "year": 2024,
    "price": 1335539,
    "originalPrice": 1462552,
    "fuel": "Petrol",
    "mileage": "11.9 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Navigation",
      "Airbags",
      "ABS",
      "Sunroof",
      "Leather Seats",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Coupe"
  },
  {
    "id": "85",
    "make": "Toyota",
    "model": "Elantra",
    "year": 2023,
    "price": 1269455,
    "originalPrice": 1375484,
    "fuel": "Diesel",
    "mileage": "23.4 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Navigation",
      "Power Steering"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "86",
    "make": "Audi",
    "model": "Malibu",
    "year": 2022,
    "price": 1205320,
    "originalPrice": 1381679,
    "fuel": "Petrol",
    "mileage": "21.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Power Steering",
      "Sunroof",
      "Navigation",
      "AC"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "87",
    "make": "Mercedes",
    "model": "X5",
    "year": 2015,
    "price": 1305917,
    "originalPrice": 1398629,
    "fuel": "Diesel",
    "mileage": "17.0 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Sunroof",
      "Navigation",
      "Power Steering",
      "Bluetooth",
      "AC",
      "Leather Seats"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "88",
    "make": "Ford",
    "model": "Malibu",
    "year": 2018,
    "price": 910727,
    "originalPrice": 1045635,
    "fuel": "Hybrid",
    "mileage": "13.6 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": true,
    "isNewArrival": false,
    "features": [
      "Airbags",
      "Leather Seats",
      "AC"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "89",
    "make": "Tesla",
    "model": "Corolla",
    "year": 2018,
    "price": 1332008,
    "originalPrice": 1528367,
    "fuel": "Hybrid",
    "mileage": "10.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Navigation",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "90",
    "make": "Tesla",
    "model": "X5",
    "year": 2022,
    "price": 1413649,
    "originalPrice": 1515000,
    "fuel": "Diesel",
    "mileage": "13.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Sunroof",
      "Navigation"
    ],
    "seating": 4,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "91",
    "make": "Toyota",
    "model": "C-Class",
    "year": 2018,
    "price": 855478,
    "originalPrice": 901202,
    "fuel": "Electric",
    "mileage": "20.2 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Navigation",
      "Sunroof",
      "ABS",
      "Bluetooth",
      "AC"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "92",
    "make": "Kia",
    "model": "Sportage",
    "year": 2013,
    "price": 713995,
    "originalPrice": 821808,
    "fuel": "Electric",
    "mileage": "17.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "ABS",
      "Power Steering"
    ],
    "seating": 5,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "93",
    "make": "Chevrolet",
    "model": "Q7",
    "year": 2014,
    "price": 733079,
    "originalPrice": 911124,
    "fuel": "Hybrid",
    "mileage": "18.2 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "Power Steering",
      "Airbags",
      "AC",
      "ABS",
      "Leather Seats",
      "Bluetooth",
      "Sunroof"
    ],
    "seating": 4,
    "transmission": "Automatic",
    "category": "Convertible"
  },
  {
    "id": "94",
    "make": "Hyundai",
    "model": "Sportage",
    "year": 2010,
    "price": 1037954,
    "originalPrice": 1140500,
    "fuel": "Electric",
    "mileage": "11.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "ABS",
      "Leather Seats",
      "Navigation",
      "Sunroof"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "95",
    "make": "Ford",
    "model": "Malibu",
    "year": 2015,
    "price": 541117,
    "originalPrice": 647473,
    "fuel": "Diesel",
    "mileage": "11.1 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Leather Seats"
    ],
    "seating": 2,
    "transmission": "Automatic",
    "category": "Hatchback"
  },
  {
    "id": "96",
    "make": "BMW",
    "model": "Mustang",
    "year": 2011,
    "price": 905566,
    "originalPrice": 1017316,
    "fuel": "Hybrid",
    "mileage": "17.3 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": true,
    "features": [
      "AC",
      "Leather Seats",
      "Navigation"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Sedan"
  },
  {
    "id": "97",
    "make": "BMW",
    "model": "Q7",
    "year": 2015,
    "price": 531260,
    "originalPrice": 725929,
    "fuel": "Diesel",
    "mileage": "17.8 km/l",
    "image": "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "ABS",
      "Leather Seats",
      "Navigation",
      "Airbags"
    ],
    "seating": 3,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "98",
    "make": "BMW",
    "model": "Elantra",
    "year": 2014,
    "price": 655809,
    "originalPrice": 834861,
    "fuel": "Petrol",
    "mileage": "15.1 km/l",
    "image": "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "AC",
      "Sunroof",
      "ABS",
      "Airbags"
    ],
    "seating": 6,
    "transmission": "Automatic",
    "category": "Sedan"
  },
  {
    "id": "99",
    "make": "Chevrolet",
    "model": "Mustang",
    "year": 2013,
    "price": 1181319,
    "originalPrice": 1363308,
    "fuel": "Electric",
    "mileage": "15.7 km/l",
    "image": "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    "seasonalOffer": true,
    "dealerPromotion": true,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Power Steering",
      "Airbags",
      "Leather Seats",
      "ABS",
      "Sunroof",
      "Navigation"
    ],
    "seating": 3,
    "transmission": "Manual",
    "category": "Hatchback"
  },
  {
    "id": "100",
    "make": "Honda",
    "model": "Mustang",
    "year": 2014,
    "price": 1379313,
    "originalPrice": 1428785,
    "fuel": "Electric",
    "mileage": "14.5 km/l",
    "image": "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg",
    "seasonalOffer": false,
    "dealerPromotion": false,
    "isHotDeal": false,
    "isNewArrival": false,
    "features": [
      "Bluetooth",
      "Navigation",
      "Sunroof"
    ],
    "seating": 6,
    "transmission": "Manual",
    "category": "Hatchback"
  }
];